// ============================================================
// 韩语语法大全 + 对话场景 + 拼写法则 + 韩国文化风俗
// 参考标准韩国语教材、延世韩国语、u校园韩语学习书籍
// ============================================================

// ===== 4. 韩语语法大全（分级分类，丰富收录） =====
window.KOREAN_GRAMMAR = [
  // --- 基础语法（1-2级） ---
  {
    level: 1, category: '助词',
    title: '은/는（主题助词）',
    pattern: '名词 + 은/는',
    meaning: '表示句子的主题，强调主语。有收音加은，无收音加는。',
    examples: [
      '저는 학생이에요.（我是学生。）',
      '이것은 책이에요.（这是书。）',
      '한국은 봄이 예뻐요.（韩国春天美。）',
    ],
    note: '은/는与이/가的区别：은/는强调主题（旧信息），이/가强调主语（新信息）。第二次提到同一主题时用은/는。',
  },
  {
    level: 1, category: '助词',
    title: '이/가（主语助词）',
    pattern: '名词 + 이/가',
    meaning: '表示句子的主语，引出新信息。有收音加이，无收音加가。',
    examples: [
      '누가 와요?（谁来？）',
      '비가 와요.（下雨。）',
      '이 꽃이 예뻐요.（这花漂亮。）',
    ],
    note: '回答"谁/什么"的问题时用이/가，因为这是新信息。',
  },
  {
    level: 1, category: '助词',
    title: '을/를（宾语助词）',
    pattern: '名词 + 을/를',
    meaning: '表示动词的宾语（动作的直接对象）。有收音加을，无收音加를。',
    examples: [
      '밥을 먹어요.（吃饭。）',
      '책을 읽어요.（读书。）',
      '물을 마셔요.（喝水。）',
    ],
    note: '口语中经常省略을/를，尤其当宾语和主语明确时。',
  },
  {
    level: 1, category: '助词',
    title: '에（位置/方向助词）',
    pattern: '名词 + 에',
    meaning: '表示方向（去哪里）、位置（在哪儿）、时间（几点/哪天）。',
    examples: [
      '학교에 가요.（去学校。）',
      '집에 있어요.（在家。）',
      '8시에 만나요.（8点见。）',
      '월요일에 쉬어요.（周一休息。）',
    ],
    note: '에用于非活动体名词后，活动体名词用한테/께（"에게/께"更正式）。',
  },
  {
    level: 1, category: '助词',
    title: '에서（起点/场所助词）',
    pattern: '名词 + 에서',
    meaning: '表示动作发生的场所（在哪儿做）或出发点（从哪儿来）。',
    examples: [
      '도서관에서 공부해요.（在图书馆学习。）',
      '중국에서 왔어요.（从中国来。）',
      '어디에서 만나요?（在哪儿见面？）',
    ],
    note: '에表示"存在/到达"，에서表示"动作发生/出发点"。对比：집에 있어요(在家) vs 집에서 쉬어요(在家休息)。',
  },
  {
    level: 1, category: '助词',
    title: '의（属格助词）',
    pattern: '名词 + 의',
    meaning: '表示所属关系（的）。口语中常省略或简化。',
    examples: [
      '나의 책（我的书）',
      '친구의 집（朋友的家）',
      '한국의 음식（韩国的食物）',
    ],
    note: '口语中"나의"常缩为"내"，"저의"缩为"제"。如"내 책"、"제 책"。',
  },
  {
    level: 1, category: '助词',
    title: '와/과（并列助词）',
    pattern: '名词 + 와/과',
    meaning: '表示并列（和/与）。有收音加과，无收音加와。口语常用하고。',
    examples: [
      '빵과 우유（面包和牛奶）',
      '사과와 바나나（苹果和香蕉）',
      '친구하고 영화를 봐요.（和朋友看电影。）',
    ],
    note: '正式书面语用与/과，口语常用하고。',
  },
  {
    level: 1, category: '助词',
    title: '도（也/也）',
    pattern: '名词 + 도',
    meaning: '表示"也/同样"，替代主题/主语/宾语助词。',
    examples: [
      '저도 학생이에요.（我也是学生。）',
      '물도 주세요.（水也请给。）',
      '오늘도 만나요.（今天也见。）',
    ],
    note: '도直接附在名词后，不再使用은/는、이/가、을/를。',
  },
  {
    level: 1, category: '助词',
    title: '만（只/仅）',
    pattern: '名词 + 만',
    meaning: '表示"只/仅"，限制范围。',
    examples: [
      '하루만 쉬어요.（只休息一天。）',
      '물만 마셔요.（只喝水。）',
      '한 번만 해 주세요.（请只做一次。）',
    ],
    note: '만直接附在名词后，可以与主题助词连用：이것만은（唯独这个）。',
  },
  {
    level: 1, category: '助词',
    title: '보다（比）',
    pattern: '名词 + 보다',
    meaning: '表示比较（比）。后面常接形容词。',
    examples: [
      '동생이 형보다 커요.（弟弟比哥哥高。）',
      '비가 눈보다 많이 와요.（雨比雪下得多。）',
      '어제보다 추워요.（比昨天冷。）',
    ],
    note: '常与"更"（더）搭配：더 예뻐요（更漂亮）。',
  },
  {
    level: 1, category: '助词',
    title: '처럼/같이（像/一样）',
    pattern: '名词 + 처럼/같이',
    meaning: '表示比喻或比较（像……一样）。',
    examples: [
      '꽃처럼 예뻐요.（像花一样美。）',
      '천사같이 착해요.（像天使一样善良。）',
      '시간이 물처럼 흘러요.（时间像水一样流。）',
    ],
    note: '처럼更偏书面，같이更偏口语。',
  },
  {
    level: 1, category: '动词变形',
    title: '-아요/어요（现在时敬语）',
    pattern: '动词词干 + 아요/어요',
    meaning: '表示现在时或一般过去时（敬语）。词干有ㅏ/ㅗ时加아요，其余加어요，하다变해요。',
    examples: [
      '가다 → 가요.（去。）',
      '먹다 → 먹어요.（吃。）',
      '공부하다 → 공부해요.（学习。）',
      '마시다 → 마셔요.（喝。）',
    ],
    note: '词干有ㅏ/ㅗ：加아요；词干有其他元音：加어요；하다：变해요。注意"마시다"→"마셔요"（ㅣ+어요→ㅕ+어요→셔요）。',
  },
  {
    level: 1, category: '动词变形',
    title: '-았/었어요（过去时）',
    pattern: '动词词干 + 았/었어요',
    meaning: '表示过去发生的事。词干有ㅏ/ㅗ时加았어요，其余加었어요，하다变했어요。',
    examples: [
      '가다 → 갔어요.（去了。）',
      '먹다 → 먹었어요.（吃了。）',
      '공부하다 → 공부했어요.（学习了。）',
      '마시다 → 마셨어요.（喝了。）',
    ],
    note: '-아요/어요的过去式即在词干和요之间插入ㅆ。',
  },
  {
    level: 1, category: '动词变形',
    title: '-을/ㄹ 거예요（将来/打算）',
    pattern: '动词词干 + 을/ㄹ 거예요',
    meaning: '表示打算、意志或推测。有收音（ㄹ除外）加을 거예요，无收音或ㄹ收音加ㄹ 거예요。',
    examples: [
      '갈 거예요.（要去。）',
      '먹을 거예요.（要吃。）',
      '공부할 거예요.（要学习。）',
      '비가 올 거예요.（会下雨。）',
    ],
    note: '疑问句"ㄹ 거예요?"用于询问对方意图："뭐 먹을 거예요?（要吃什么？）"',
  },
  {
    level: 1, category: '动词变形',
    title: '-지 않다/안（否定）',
    pattern: '动词词干 + 지 않다 / 안 + 动词',
    meaning: '表示否定（不/没）。"지 않다"为长形否定，"안"为短形否定。',
    examples: [
      '안 가요.（不去。）',
      '먹지 않아요.（不吃。）',
      '안 먹어요.（没吃。）',
      '공부하지 않아요.（不学习。）',
    ],
    note: '안不能与있다/없다/계시다连用，需用지 않다。"안 좋아요"是错的，应为"좋지 않아요"。',
  },
  {
    level: 1, category: '动词变形',
    title: '못（不能）',
    pattern: '못 + 动词 / 动词词干 + 지 못하다',
    meaning: '表示"不能/做不到"（客观上无法做到）。',
    examples: [
      '못 가요.（不能去。）',
      '못 먹어요.（不能吃。）',
      '오지 못해요.（不能来。）',
      '한국어를 잘 못해요.（韩语说不好。）',
    ],
    note: '안是主观不去做，못是客观上做不到。对比：안 가요(不去) vs 못 가요(不能去)。',
  },
  {
    level: 1, category: '句型',
    title: '-고 싶다（想做）',
    pattern: '动词词干 + 고 싶다',
    meaning: '表示第一人称的愿望（想做某事）。',
    examples: [
      '가고 싶어요.（想去。）',
      '먹고 싶어요.（想吃。）',
      '한국에 가고 싶어요.（想去韩国。）',
    ],
    note: '第三人称（他/她想）要用"-고 싶어하다"：친구가 가고 싶어해요.',
  },
  {
    level: 1, category: '句型',
    title: '-고（并列）',
    pattern: '动词/形容词词干 + 고',
    meaning: '表示并列（又……又……，然后）。',
    examples: [
      '사과를 사고 배를 샀어요.（买了苹果和梨。）',
      '예쁘고 똑똑해요.（又漂亮又聪明。）',
      '밥을 먹고 가요.（吃饭然后去。）',
    ],
    note: '-고用于动词表示先后顺序；用于形容词表示并列属性。',
  },
  {
    level: 1, category: '句型',
    title: '-아서/어서（原因/顺序）',
    pattern: '动词/形容词词干 + 아서/어서',
    meaning: '表示原因或先后顺序（因为……所以；做了……然后）。',
    examples: [
      '비가 와서 안 가요.（下雨所以不去。）',
      '피곤해서 일찍 자요.（太累所以早睡。）',
      '도서관에 가서 공부해요.（去图书馆然后学习。）',
    ],
    note: '-아서/어서不与过去时制词尾(았/었)连用。不能说"비가 왔어서"。',
  },
  {
    level: 1, category: '句型',
    title: '名词 + 이에요/예요（是）',
    pattern: '名词 + 이에요/예요',
    meaning: '表示"是……"。有收音加이에요，无收音加예요。',
    examples: [
      '저는 학생이에요.（我是学生。）',
      '이것은 사과예요.（这是苹果。）',
      '친구는 의사예요.（朋友是医生。）',
    ],
    note: '否定形式：名词 +이/가 + 아니에요。如"학생이 아니에요.（不是学生。）"',
  },
  {
    level: 1, category: '句型',
    title: '있다/없다（有/没有）',
    pattern: '名词 + 이/가 있다/없다',
    meaning: '表示存在（有/没有）。',
    examples: [
      '시간이 있어요.（有时间。）',
      '돈이 없어요.（没有钱。）',
      '방에 사람이 있어요.（房间有人。）',
      '책상 위에 책이 없어요.（桌上没有书。）',
    ],
    note: '表示位置的"在"也用있다：학교에 있어요（在学校）。',
  },
  // --- 中级语法（3-4级） ---
  {
    level: 3, category: '句型',
    title: '-게 되다（变得）',
    pattern: '动词词干 + 게 되다',
    meaning: '表示状态变化（变得……，到了……的地步）。',
    examples: [
      '한국어를 하게 되었어요.（会说韩语了。）',
      '회사를 그만두게 되었어요.（不得不辞职了。）',
      '알게 되었어요.（知道了。）',
    ],
    note: '强调由于外部原因导致的变化，不是主观意愿。',
  },
  {
    level: 3, category: '句型',
    title: '-아/어지다（变得）',
    pattern: '形容词词干 + 아/어지다',
    meaning: '表示状态变化（变得……）。',
    examples: [
      '날씨가 추워져요.（天气变冷了。）',
      '건강해져요.（变健康了。）',
      '예뻐져요.（变漂亮了。）',
    ],
    note: '用于形容词，表示状态转变。춥다→추워지다, 좋다→좋아지다, 크다→커지다。',
  },
  {
    level: 3, category: '句型',
    title: '-기 때문에（因为）',
    pattern: '动词/形容词词干 + 기 때문에',
    meaning: '表示原因（因为……）。比-아서/어서更正式。',
    examples: [
      '비가 오기 때문에 안 가요.（因为下雨所以不去。）',
      '피곤하기 때문에 쉴 거예요.（因为太累所以要休息。）',
      '좋기 때문에 추천해요.（因为好所以推荐。）',
    ],
    note: '名词后直接用"때문에"：피곤해서가 아니라 돈 때문에...（不是因为累而是因为钱……）。',
  },
  {
    level: 3, category: '句型',
    title: '-기로 하다（决定）',
    pattern: '动词词干 + 기로 하다',
    meaning: '表示决定（决定做某事）。',
    examples: [
      '내일 가기로 했어요.（决定明天去。）',
      '한국어를 배우기로 했어요.（决定学韩语。）',
      '다이어트를 하기로 했어요.（决定减肥。）',
    ],
    note: '主语为第一人称时表示"我/我们决定"；主语为他人时表示"他决定"。',
  },
  {
    level: 3, category: '句型',
    title: '-는 것（名词化）',
    pattern: '动词词干 + 는 것',
    meaning: '将动词名词化（做某事这件事）。',
    examples: [
      '공부하는 것이 중요해요.（学习很重要。）',
      '운동하는 것을 좋아해요.（喜欢运动。）',
      '요리하는 것에 관심 있어요.（对做饭感兴趣。）',
    ],
    note: '过去时用"-(으)ㄴ 것"，将来时用"-(으)ㄹ 것"。',
  },
  {
    level: 3, category: '句型',
    title: '-에 의하면（根据）',
    pattern: '名词 + 에 의하면',
    meaning: '表示依据（根据……）。',
    examples: [
      '일기예보에 의하면 비가 온대요.（据天气预报说会下雨。）',
      '뉴스에 의하면 경기가 좋아진대요.（据新闻说经济好转。）',
    ],
    note: '常与间接引语"-대요"连用。',
  },
  {
    level: 3, category: '句型',
    title: '-을/ㄹ 수 있다（能）',
    pattern: '动词词干 + 을/ㄹ 수 있다',
    meaning: '表示能力或可能性（能/可以）。',
    examples: [
      '한국어를 할 수 있어요.（会说韩语。）',
      '내일 갈 수 있어요.（明天能去。）',
      '도와줄 수 있어요?（能帮一下吗？）',
    ],
    note: '否定形式"을/ㄹ 수 없다"：못 할 수 없어요? → 할 수 없어요.（不能做。）',
  },
  {
    level: 3, category: '句型',
    title: '-지만（但是）',
    pattern: '动词/形容词/名词 + 지만',
    meaning: '表示转折（但是/可是）。',
    examples: [
      '비가 오지만 가요.（虽然下雨但要去。）',
      '작지만 예뻐요.（虽小但漂亮。）',
      '학생이지만 일해요.（虽然是学生但在工作。）',
    ],
    note: '可以与过去时连用：갔지만（虽然去了……）。',
  },
  {
    level: 3, category: '句型',
    title: '-으면서（同时）',
    pattern: '动词词干 + 으면서',
    meaning: '表示同时进行（一边……一边……）。',
    examples: [
      '음악을 들으면서 공부해요.（边听音乐边学习。）',
      '걸으면서 이야기해요.（边走边聊。）',
      '밥을 먹으면서 TV를 봐요.（边吃饭边看电视。）',
    ],
    note: '主语相同，两个动作同时进行。',
  },
  {
    level: 3, category: '句型',
    title: '-다가（转换）',
    pattern: '动词词干 + 다가',
    meaning: '表示动作中途转换（做着……后来转做别的）。',
    examples: [
      '길을 걷다가 넘어졌어요.（走路时摔倒了。）',
      '책을 읽다가 잠들었어요.（看书时睡着了。）',
      '가다가 돌아왔어요.（走着走着返回了。）',
    ],
    note: '前一个动作中断，转向后一个动作。',
  },
  {
    level: 3, category: '句型',
    title: '-아/어야 하다（必须）',
    pattern: '动词词干 + 아/어야 하다',
    meaning: '表示义务或必要（必须/应该）。',
    examples: [
      '빨리 가야 해요.（必须快去。）',
      '약을 먹어야 해요.（必须吃药。）',
      '한국어를 공부해야 해요.（必须学韩语。）',
    ],
    note: '口语简化为"-아/어야 해요"。',
  },
  {
    level: 3, category: '句型',
    title: '-보이다（看起来）',
    pattern: '形容词/名词 + 보이다',
    meaning: '表示看起来（看起来……）。',
    examples: [
      '예뻐 보여요.（看起来漂亮。）',
      '건강해 보여요.（看起来健康。）',
      '맛있어 보여요.（看起来好吃。）',
    ],
    note: '注意区别于动词"보다"（看）。',
  },
  {
    level: 3, category: '间接引语',
    title: '-라고/다고 하다（间接引语）',
    pattern: '引语 + 라고/다고 하다',
    meaning: '转述别人的话。',
    examples: [
      '친구가 온다고 했어요.（朋友说来。）',
      '내일 비가 온대요.（明天据说下雨。）',
      '"안녕"이라고 했어요.（说了"你好"。）',
    ],
    note: '动词词干+다고(고)，命令句"-라고"，疑问句"-냐고"。',
  },
  {
    level: 3, category: '句型',
    title: '-느라고（目的）',
    pattern: '动词词干 + 느라고',
    meaning: '表示为了某目的而做事（通常带来负面结果）。',
    examples: [
      '공부하느라고 바빠요.（因为学习而忙。）',
      '요리하느라고 늦었어요.（因为做饭而迟了。）',
      '일하느라고 못 갔어요.（因为工作而没去成。）',
    ],
    note: '主语须为第一/二人称，且前后主语相同。',
  },
  {
    level: 4, category: '句型',
    title: '-기는 하다（倒是）',
    pattern: '动词/形容词词干 + 기는 하다',
    meaning: '表示让步（倒是……但）。',
    examples: [
      '예쁘기는 한데 너무 비싸요.（漂亮倒是漂亮，但太贵。）',
      '맛있기는 해요.（好吃倒是好吃。）',
      '가기는 가요.（去倒是去。）',
    ],
    note: '承认某事实，但暗示有保留意见。',
  },
  {
    level: 4, category: '句型',
    title: '-을/ㄹ 뻔하다（差点）',
    pattern: '动词词干 + 을/ㄹ 뻔하다',
    meaning: '表示差点发生（差点就……）。',
    examples: [
      '넘어질 뻔했어요.（差点摔倒。）',
      '지각할 뻔했어요.（差点迟到。）',
      '깜빡 잊을 뻔했어요.（差点忘了。）',
    ],
    note: '通常与"하마터면"（差点）连用：하마터면 죽을 뻔했어요.',
  },
  {
    level: 4, category: '句型',
    title: '-을/ㄹ 만하다（值得）',
    pattern: '动词词干 + 을/ㄹ 만하다',
    meaning: '表示值得（值得做）。',
    examples: [
      '볼 만해요.（值得看。）',
      '먹을 만해요.（值得吃。）',
      '갈 만해요.（值得去。）',
    ],
    note: '也可以表示"能/可以"：할 만해요（能做到）。',
  },
  {
    level: 4, category: '句型',
    title: '-다 보면（做着做着就）',
    pattern: '动词词干 + 다 보면',
    meaning: '表示反复做某事过程中产生新情况。',
    examples: [
      '하다 보면 알게 될 거예요.（做着做着就知道了。）',
      '살다 보면 좋은 일이 있어요.（活着就有好事。）',
      '만나다 보면 친해질 거예요.（见着见着就会亲近。）',
    ],
    note: '强调反复或持续的过程中出现变化。',
  },
  {
    level: 4, category: '句型',
    title: '-을/ㄹ 정도（程度）',
    pattern: '动词词干 + 을/ㄹ 정도',
    meaning: '表示程度（到了……的程度）。',
    examples: [
      '울 정도로 슬퍼요.（伤心到要哭的程度。）',
      '못 먹을 정도로 많아요.（多到吃不完。）',
      '숨을 못 쉴 정도예요.（到喘不过气的程度。）',
    ],
    note: '常与"로"连用表示方式：-을 정도로。',
  },
  {
    level: 4, category: '句型',
    title: '-을/ㄹ까 봐（担心）',
    pattern: '动词词干 + 을/ㄹ까 봐',
    meaning: '表示担心（怕……）。',
    examples: [
      '늦을까 봐 빨리 갔어요.（怕迟到所以快去了。）',
      '잊을까 봐 메모했어요.（怕忘记所以记下来了。）',
      '비가 올까 봐 우산을 가져요.（怕下雨带了伞。）',
    ],
    note: '表示对可能发生之事的担心。',
  },
  // --- 高级语法（5-6级） ---
  {
    level: 5, category: '句型',
    title: '-을/ㄹ 뿐만 아니라（不仅）',
    pattern: '动词/形容词/名词 + 을/ㄹ 뿐만 아니라',
    meaning: '表示"不仅……而且"。',
    examples: [
      '예쁠 뿐만 아니라 똑똑해요.（不仅漂亮而且聪明。）',
      '한국어뿐만 아니라 일본어도 해요.（不仅韩语还日语。）',
      '공부도 잘할 뿐만 아니라 운동도 잘해요.（不仅学习好运动也好。）',
    ],
    note: '用于递进补充。',
  },
  {
    level: 5, category: '句型',
    title: '-을/ㄹ 뻔했다가（差一点就）',
    pattern: '动词词干 + 을/ㄹ 뻔했다가',
    meaning: '表示差一点发生某事（结果又改变）。',
    examples: [
      '넘어질 뻔했다가 살았어요.（差点摔倒但没事了。）',
      '죽을 뻔했다가 살았어요.（差点死了但活下来了。）',
    ],
    note: '比"-을 뻔하다"更强调事态变化。',
  },
  {
    level: 5, category: '句型',
    title: '-기 나름이다（取决于）',
    pattern: '动词词干 + 기 나름이다',
    meaning: '表示取决于（要看……）。',
    examples: [
      '성공하느냐 못 하느냐는 노력하기 나름이에요.（成功与否取决于努力。）',
      '맛있기 나름이에요.（要看做得好不好。）',
    ],
    note: '强调结果取决于某条件。',
  },
  {
    level: 5, category: '句型',
    title: '-을/ㄹ 정도로（到……程度）',
    pattern: '动词词干 + 을/ㄹ 정도로',
    meaning: '表示达到某种程度。',
    examples: [
      '울 정도로 기뻐요.（高兴到哭的程度。）',
      '숨을 못 쉴 정도로 더워요.（热到喘不过气。）',
      '깜짝 놀랄 정도로 비싸요.（贵到令人惊讶。）',
    ],
    note: '比"-을 정도"更强调程度。',
  },
  {
    level: 5, category: '句型',
    title: '-는 바람에（由于）',
    pattern: '动词词干 + 는 바람에',
    meaning: '表示因为意外原因导致负面结果。',
    examples: [
      '비가 오는 바람에 못 갔어요.（因为下雨没能去。）',
      '늦잠을 자는 바람에 지각했어요.（因为睡过头迟到了。）',
      '길이 막히는 바람에 늦었어요.（因为堵车迟到了。）',
    ],
    note: '通常用于说话人无法控制的情况，结果多为负面。',
  },
  {
    level: 5, category: '句型',
    title: '-ㄴ/는 척하다（装作）',
    pattern: '动词词干 + ㄴ/는 척하다',
    meaning: '表示假装（装作……）。',
    examples: [
      '아는 척했어요.（装作知道。）',
      '자는 척했어요.（装作在睡。）',
      '안 본 척했어요.（装作没看见。）',
    ],
    note: '形容词用"ㄴ 척"，动词现在用"는 척"，过去用"ㄴ 척"。',
  },
  {
    level: 6, category: '句型',
    title: '-을/ㄹ지라도（即使）',
    pattern: '动词词干 + 을/ㄹ지라도',
    meaning: '表示让步（即使……也）。比"-어도"更书面正式。',
    examples: [
      '죽을지라도 포기 안 해요.（即使死也不放弃。）',
      '힘들지라도 끝까지 해요.（即使辛苦也要做到最后。）',
      '비가 올지라도 가요.（即使下雨也去。）',
    ],
    note: '书面语，口语常用"-어도"。',
  },
  {
    level: 6, category: '句型',
    title: '-ㄴ/는단 말이야（强调）',
    pattern: '动词词干 + ㄴ/는단 말이야',
    meaning: '强调语气（就是说……啊）。',
    examples: [
      '안 된단 말이야!（就是不行啊！）',
      '하고 싶단 말이야.（就是想做啊。）',
    ],
    note: '口语强调表达，带感情色彩。',
  },
  {
    level: 6, category: '句型',
    title: '-느니보다（与其……不如）',
    pattern: '动词词干 + 느니보다',
    meaning: '表示比较（与其……不如）。',
    examples: [
      '쉬느니보다 일하는 게 나아요.（与其休息不如工作。）',
      '갔느니보다 안 가는 게 좋아요.（与其去不如不去。）',
    ],
    note: '高级比较句型，用于选择更优方案。',
  },
  {
    level: 6, category: '句型',
    title: '-을/ㄹ망정（即使）',
    pattern: '动词词干 + 을/ㄹ망정',
    meaning: '表示让步（即使……也）。比"-어도"更正式。',
    examples: [
      '비가 올망정 가요.（即使下雨也去。）',
      '힘들망정 포기 안 해요.（即使辛苦也不放弃。）',
    ],
    note: '常用于书面或正式文体。',
  },
  {
    level: 6, category: '句型',
    title: '-거늘（因为）',
    pattern: '动词/形容词词干 + 거늘',
    meaning: '表示理由（既然……就）。',
    examples: [
      '이미 정했거늘 바꿀 수 없어요.（既然已决定就不能改。）',
      '약속했거늘 지켜야 해요.（既然约定了就该遵守。）',
    ],
    note: '书面正式，带有"理所当然"语气。',
  },
  {
    level: 6, category: '句型',
    title: '-ㄴ들（即使）',
    pattern: '动词/形容词词干 + ㄴ들',
    meaning: '表示让步（即使……又）。',
    examples: [
      '어찌 안 가겠느뇨, 안 간들 어떡해요.（即使不去又能怎样。）',
      '예쁜들 제일 예쁜가요.（漂亮又怎样，是最漂亮的吗。）',
    ],
    note: '古风/正式文体，现代口语极少用。',
  },
];

// ===== 5. 日常对话场景（场景丰富，对话联动切换） =====
window.DIALOGUE_SCENES = [
  {
    id: 'greeting', name: '初次见面打招呼', icon: '👋',
    description: '初次与韩国人见面时的自我介绍和寒暄',
    dialogues: [
      { speaker: 'A', kr: '안녕하세요! 처음 뵙겠습니다.', roman: 'annyeonghaseyo! cheoeum boepgesseumnida.', zh: '你好！初次见面。', note: '"처음 뵙겠습니다"是正式的初次见面用语，比"만나서 반갑습니다"更谦逊。' },
      { speaker: 'B', kr: '안녕하세요! 만나서 반갑습니다.', roman: 'annyeonghaseyo! mannaseo bangapseumnida.', zh: '你好！很高兴见到你。', note: '"만나서 반갑습니다"是标准的见面问候。' },
      { speaker: 'A', kr: '제 이름은 김민수입니다. 잘 부탁드립니다.', roman: 'je ireumeun gim minsubimnida. jal butodeurimnida.', zh: '我叫金敏秀。请多关照。', note: '"잘 부탁드립니다"是韩国人初次见面的经典寒暄，相当于"请多关照"。' },
      { speaker: 'B', kr: '저는 이영희라고 합니다. 잘 부탁해요.', roman: 'jeo-neun iyeonghirago hamnida. jal butohaeyo.', zh: '我叫李英姬。请多关照。', note: '"라고 합니다"用于介绍自己名字或身份。' },
      { speaker: 'A', kr: '혹시 한국어를 공부하세요?', roman: 'hoksi hangukeoreul gongbuhaseyo?', zh: '请问你在学韩语吗？', note: '"혹시"是委婉提问的开场白，相当于"请问/是不是"。' },
      { speaker: 'B', kr: '네, 요즘 열심히 배우고 있어요.', roman: 'ne, yojeum yeolsimhi baeugo isseoyo.', zh: '是的，最近在努力学习。', note: '"-(으)고 있어요"表示正在进行。' },
    ],
  },
  {
    id: 'restaurant', name: '餐厅点餐', icon: '🍽️',
    description: '在韩国餐厅用餐时的点餐和沟通',
    dialogues: [
      { speaker: 'Staff', kr: '몇 분이세요?', roman: 'myeon buniseyo?', zh: '请问几位？', note: '韩国餐厅入座前服务员会先问人数。' },
      { speaker: 'You', kr: '두 명이요. 자리 있나요?', roman: 'du myeongiyo. jari innayo?', zh: '两位。有位置吗？', note: '回答人数常用"명"或"분"（敬语）。' },
      { speaker: 'Staff', kr: '이쪽으로 앉으세요. 여기 메뉴입니다.', roman: 'ijjogeuro anjeuseyo. yeogi menyuibnida.', zh: '请这边坐。这是菜单。', note: '"-(으)세요"为命令句的敬语形式。' },
      { speaker: 'You', kr: '비빔밥 하나하고 김치찌개 하나 주세요.', roman: 'bibimbap hanahago kimchijjigae hana juseyo.', zh: '请给我一个拌饭和一个泡菜汤。', note: '点餐时"하고"表示并列，"주세요"是"请给"的敬语。' },
      { speaker: 'Staff', kr: '매운 음식 괜찮으세요?', roman: 'maeun eumsik gwaenchaneuseyo?', zh: '能吃辣吗？', note: '韩国菜偏辣，服务员通常会确认。' },
      { speaker: 'You', kr: '네, 괜찮아요. 물 좀 더 주세요.', roman: 'ne, gwaenchayo. mul jom deo juseyo.', zh: '可以。请多给点水。', note: '"좀"是"一点"的意思，用于委婉请求。' },
      { speaker: 'You', kr: '여기서 계산할게요.', roman: 'yeogiseo gyesanhalgeyo.', zh: '在这里结账。', note: '"-(으)ㄹ게요"表示说话人的意志。"여기서"表示在座位上结账，韩国有堂食位结账文化。' },
      { speaker: 'Staff', kr: '감사합니다. 안녕히 가세요.', roman: 'gamsahamnida. annyeonghi gaseyo.', zh: '谢谢。慢走。', note: '"안녕히 가세요"对离开的人说，"안녕히 계세요"对留下的人说。' },
    ],
  },
  {
    id: 'shopping', name: '购物砍价', icon: '🛍️',
    description: '在韩国市场或商店购物时的对话',
    dialogues: [
      { speaker: 'You', kr: '이거 얼마예요?', roman: 'igeo eolmayeyo?', zh: '这个多少钱？', note: '"얼마"是问价钱的常用词。' },
      { speaker: 'Staff', kr: '3만 원이에요.', roman: 'saman wonieyo.', zh: '3万韩元。', note: '韩币单位"원"，数字后直接加"원"。' },
      { speaker: 'You', kr: '너무 비싸요. 좀 깎아주세요.', roman: 'neomu bissayo. jom kkakajuseyo.', zh: '太贵了。请便宜点。', note: '"깎다"是砍价时用的高频动词。' },
      { speaker: 'Staff', kr: '죄송하지만 정가입니다.', roman: 'joesonghajiman jeonggabimnida.', zh: '抱歉，这是定价。', note: '"정가"表示不二价，大型店或连锁店通常不议价。' },
      { speaker: 'You', kr: '그럼 다른 걸로 볼게요.', roman: 'geureom dareun geollo bolgeyo.', zh: '那我看别的吧。', note: '"-(으)ㄹ게요"表示意愿。"다른 걸로"是"用别的"。' },
      { speaker: 'Staff', kr: '이건 세일 중이라 2만 원이에요.', roman: 'igeon seil jungira iman wonieyo.', zh: '这个正在促销，2万韩元。', note: '"세일 중"是英语借词，"중"表示"中"（进行中）。' },
      { speaker: 'You', kr: '좋아요. 이걸로 주세요.', roman: 'joayo. igeollo juseyo.', zh: '好。就要这个。', note: '"-(으)로 주세요"是"请给我……"的标准句式。' },
      { speaker: 'Staff', kr: '영수증 필요하세요?', roman: 'yeongsujeung piryohaseyo?', zh: '需要收据吗？', note: '韩国购物后通常询问是否需要收据。' },
    ],
  },
  {
    id: 'direction', name: '问路指路', icon: '🗺️',
    description: '在韩国街头问路或给他人指路',
    dialogues: [
      { speaker: 'You', kr: '저기요, 역이 어디에 있어요?', roman: 'jeogiyo, yeogi eodie isseoyo?', zh: '打扰一下，火车站在哪里？', note: '"저기요"是叫住陌生人时的礼貌用语。' },
      { speaker: 'Local', kr: '어느 역이요?', roman: 'eoneu yeogiyo?', zh: '哪个站？', note: '"어느"用于在多个中选择。' },
      { speaker: 'You', kr: '서울역이요.', roman: 'seoullyeogiyo.', zh: '首尔站。', note: '回答时常用"-(이)요"省略助词。' },
      { speaker: 'Local', kr: '이 길로 쭉 가시면 오른쪽에 있어요.', roman: 'i gillo jjukkasimyeon oreunjjoge isseoyo.', zh: '沿这条路直走，就在右边。', note: '"쭉"是"一直"的口语化，"가시면"是"가다"的敬语条件式。' },
      { speaker: 'You', kr: '얼마나 걸려요?', roman: 'eolmana geollyeoyo?', zh: '要走多久？', note: '"걸리다"表示花费时间。' },
      { speaker: 'Local', kr: '걸어서 10분쯤 걸려요.', roman: 'georeoseo sipbunjjum geollyeoyo.', zh: '走路大概10分钟。', note: '"-(으)ㅁ"是名词化，"쯤"表示"大概"。' },
      { speaker: 'You', kr: '감사합니다! 잘 찾아갈게요.', roman: 'gamsahamnida! jal chajagalgeyo.', zh: '谢谢！我会找过去的。', note: '"잘 찾아가다"表示自己找路过去。' },
      { speaker: 'Local', kr: '천만에요. 조심히 가세요.', roman: 'cheonmaneyo. josimhi gaseyo.', zh: '不客气。路上小心。', note: '"천만에요"是"不客气"的正式说法，"조심히 가세요"是道别用语。' },
    ],
  },
  {
    id: 'hotel', name: '酒店入住', icon: '🏨',
    description: '在韩国酒店办理入住和退房',
    dialogues: [
      { speaker: 'You', kr: '체크인하고 싶어요.', roman: 'chekeu-inhago sipeoyo.', zh: '我想办理入住。', note: '"체크인"是英语借词。' },
      { speaker: 'Staff', kr: '예약하셨어요?', roman: 'yeyakahasyeosseoyo?', zh: '请问有预约吗？', note: '"-(으)셨-"是过去时的敬语词尾。' },
      { speaker: 'You', kr: '네, 김민수 이름으로 예약했어요.', roman: 'ne, gimminsu ireumeuro yeyakaesseoyo.', zh: '有，用金敏秀的名字预约的。', note: '"-(으)로"表示用某信息。' },
      { speaker: 'Staff', kr: '넷, 확인해 보겠습니다. 3박이 맞으세요?', roman: 'net, hwaginhae bogesseumnida. sambagi majeuseyo?', zh: '好的，我来确认。住3晚对吗？', note: '"-(으)시겠-"是"确认"的敬语形式。' },
      { speaker: 'You', kr: '맞아요. 3박이에요.', roman: 'majayo. sambagieyo.', zh: '对，3晚。', note: '"박"是"晚"的量词。' },
      { speaker: 'Staff', kr: '방 열쇠 여기 있습니다. 405호입니다.', roman: 'bang yeolsoe yeogi isseumnida. saryongo ibimnida.', zh: '这是房间钥匙。405号房。', note: '房间号读法：405读"사백오"，但房间号常说"사공오"。' },
      { speaker: 'You', kr: '조식 몇 시부터예요?', roman: 'josik myeon sibuteoyeyo?', zh: '早餐几点开始？', note: '酒店早餐叫"조식"（朝食）。' },
      { speaker: 'Staff', kr: '7시부터 10시까지 레스토랑에서 가능합니다.', roman: 'ilgopsibuteo yeolsikkaji leseutorangeseo ganeunghamnida.', zh: '7点到10点在餐厅。', note: '"-(으)ㅁ"表示可能，" 가능합니다"表示"可以"。' },
    ],
  },
  {
    id: 'airport', name: '机场值机', icon: '✈️',
    description: '在韩国机场办理登机和海关对话',
    dialogues: [
      { speaker: 'Staff', kr: '여권과 티켓 보여주세요.', roman: 'yeogwangwa tikes boyeojuseyo.', zh: '请出示护照和机票。', note: '"여권"是护照，"티켓"是英语借词。' },
      { speaker: 'You', kr: '여기 있습니다.', roman: 'yeogi isseumnida.', zh: '在这里。', note: '递交物品时的常用语。' },
      { speaker: 'Staff', kr: '창가 자리랑 통로 자리 중 어디 선호하세요?', roman: 'changga jarirang tongro jari jung eodi seonhohaseyo?', zh: '靠窗和靠过道，你倾向哪个？', note: '"-(으)ㄹ래요/세요"询问偏好。' },
      { speaker: 'You', kr: '창가 자리로 주세요.', roman: 'changga jarillo juseyo.', zh: '请给靠窗的位置。', note: '韩国人通常首选靠窗位置。' },
      { speaker: 'Staff', kr: '수하물 있으세요?', roman: 'suhamul isseuseyo?', zh: '有托运行李吗？', note: '"수하물"是托运行李的正式说法。' },
      { speaker: 'You', kr: '네, 이 가방 하나 부탁드립니다.', roman: 'ne, i gabang hana butadeurimnida.', zh: '有的，这件行李拜托了。', note: '"부탁드리다"是"拜托"的敬语。' },
      { speaker: 'Staff', kr: '이곳에 올려주세요. 22kg입니다.', roman: 'igose ollyeojuseyo. ishipikgimnida.', zh: '请放在这里。22公斤。', note: '行李限重通常为20-23公斤。' },
      { speaker: 'Staff', kr: '탑승구는 23번, 탑승 시간은 9시 30분입니다.', roman: 'tapseunggueneun isipsambeon, tapseung siganeun ahopsi samsipbunimnida.', zh: '登机口23号，登机时间9:30。', note: '"탑승"是登机，"구"是"口"。' },
    ],
  },
  {
    id: 'friends', name: '朋友约会', icon: '🤝',
    description: '和朋友约周末或安排见面的对话',
    dialogues: [
      { speaker: 'A', kr: '이번 주말에 시간 있어?', roman: 'ibeon jumae sigan isseo?', zh: '这周末有空吗？', note: '朋友之间用非敬语"-어"结尾。' },
      { speaker: 'B', kr: '응, 왜?', roman: 'eung, wae?', zh: '嗯，怎么了？', note: '"응"是"是的"的非敬语，"왜"是"为什么/怎么了"。' },
      { speaker: 'A', kr: '같이 영화 볼래?', roman: 'gachi yeongha bollae?', zh: '一起看电影吗？', note: '"-(으)ㄹ래"是朋友间提议做某事。' },
      { speaker: 'B', kr: '좋아! 뭐 볼 건데?', roman: 'joa! mwo bol geonde?', zh: '好呀！看什么？', note: '"-(으)ㄹ 건데"询问意向。' },
      { speaker: 'A', kr: '새로 나온 한국 영화 어때?', roman: 'saero naon hanguk yeonghwa eottae?', zh: '新上的韩国电影怎么样？', note: '"어때"询问评价或意见。' },
      { speaker: 'B', kr: '좋지! 몇 시에 만날까?', roman: 'jotji! myeon sie mannalkka?', zh: '好啊！几点见？', note: '"-(으)ㄹ까"用于提议。' },
      { speaker: 'A', kr: '3시에 강남역에서 만나자.', roman: 'sesie gangnamyeogeseo mannaja.', zh: '3点在江南站见吧。', note: '"-자"是朋友间"一起做"的提议式。' },
      { speaker: 'B', kr: '알았어. 늦지 마!', roman: 'arasseo. neutji ma!', zh: '知道了。别迟到！', note: '"-(으)지 마"是"不要"的命令式。' },
    ],
  },
  {
    id: 'taxi', name: '打车出行', icon: '🚕',
    description: '在韩国打车和与司机对话',
    dialogues: [
      { speaker: 'You', kr: '강남역 가주세요.', roman: 'gangnamyeong gajuseyo.', zh: '请去江南站。', note: '上车后直接说目的地+"가주세요/가주십시오"。' },
      { speaker: 'Driver', kr: '네, 알겠습니다. 어디로 가요?', roman: 'ne, algeseumnida. eodiro gayo?', zh: '好的。走哪条路？', note: '韩国司机通常会问走哪条路。' },
      { speaker: 'You', kr: '빠른 길로 가주세요.', roman: 'ppareun gillo gajuseyo.', zh: '请走快的路。', note: '"빠르다"是"快"。' },
      { speaker: 'Driver', kr: '지금 길이 막혀서 한강대교로 가는 게 낫겠어요.', roman: 'jigeum giri makyeseo hangangdaegoro ganeun ge natgesseoyo.', zh: '现在堵车，走汉江大桥比较好。', note: '"-(으)ㄴ/는 게 낫다"表示"……更好"。' },
      { speaker: 'You', kr: '네, 그렇게 해주세요. 얼마나 걸려요?', roman: 'ne, geureoke haejuseyo. eolmana geollyeoyo?', zh: '好的，就这样。大概多久？', note: '询问车费或时间。' },
      { speaker: 'Driver', kr: '20분쯤 걸릴 것 같아요.', roman: 'isipbunjjum geollil geot gatayo.', zh: '大概20分钟。', note: '"-(으)ㄹ 것 같다"表示推测。' },
      { speaker: 'You', kr: '여기 세워주세요.', roman: 'yeogi sewojuseyo.', zh: '请在这里停。', note: '下车时说"세워주세요"（请停）。' },
      { speaker: 'Driver', kr: '현금이요? 카드요?', roman: 'hyeongeumeyo? kadeuyo?', zh: '现金还是卡？', note: '韩国出租车普遍接受卡支付。' },
    ],
  },
  {
    id: 'office', name: '职场沟通', icon: '💼',
    description: '在公司与同事或上司沟通',
    dialogues: [
      { speaker: 'Colleague', kr: '회의 몇 시에 해요?', roman: 'hoeui myeon sie haeyo?', zh: '会议几点开？', note: '职场同事间用"-어요"半语。' },
      { speaker: 'You', kr: '3시에 회의실에서 할 거예요.', roman: 'sesie hoeuisireseo hal geoyeyo.', zh: '3点在会议室。', note: '"회의실"是会议室。' },
      { speaker: 'Boss', kr: '김 대리, 보고서 다 됐어요?', roman: 'gim daeri, bogoseo da dwaesseoyo?', zh: '金代理，报告好了吗？', note: '"대리"是韩国公司职位，仅次于"과장"。"다 됐어요"表示"完成了"。' },
      { speaker: 'You', kr: '네, 거의 다 했어요. 오늘까지 제출할게요.', roman: 'ne, geoui da haesseoyo. oneulkkaji jechulhalgeyo.', zh: '是的，差不多完成了。今天提交。', note: '"거의"表示"差不多/几乎"。' },
      { speaker: 'Colleague', kr: '점심 같이 먹을래요?', roman: 'jeomsim gachi meogeullaeyo?', zh: '一起吃午饭吗？', note: '韩国职场有集体午餐文化。' },
      { speaker: 'You', kr: '좋아요. 뭐 먹을까요?', roman: 'joayo. mwo meogeulkkayo?', zh: '好啊。吃什么？', note: '"-(으)ㄹ까요"用于委婉提议。' },
      { speaker: 'Colleague', kr: '오늘 날씨 추우니까 국물 어때요?', roman: 'oneul nalssi chuunikke gukmul eottaeyo?', zh: '今天冷，喝汤怎么样？', note: '"-(으)니까"表示原因（因为……所以）。' },
      { speaker: 'You', kr: '좋아요. 김치찌개로 하죠.', roman: 'joayo. kimchijjigaero hajyo.', zh: '好的。就吃泡菜汤吧。', note: '"-(으)로 하다"表示"决定用……"。' },
    ],
  },
  {
    id: 'phone', name: '电话沟通', icon: '📞',
    description: '在韩国打电话的标准对话',
    dialogues: [
      { speaker: 'You', kr: '여보세요? 거기 영희 씨 댁이죠?', roman: 'yeoboseyo? geogi yeonghi ssi jekijyo?', zh: '喂？是英姬家吗？', note: '"여보세요"是韩国电话标准问候语。' },
      { speaker: 'Other', kr: '네, 맞는데요. 누구세요?', roman: 'ne, manneundeyo. nuguseyo?', zh: '是的。您是？', note: '"-(으)ㄴ데요"用于确认信息并询问对方。' },
      { speaker: 'You', kr: '안녕하세요. 민수라고 합니다. 영희 씨 있어요?', roman: 'annyeonghaseyo. minsurago hamnida. yeonghi ssi isseoyo?', zh: '你好。我叫敏秀。英姬在吗？', note: '打电话找人的标准句型"XX 있어요?"。' },
      { speaker: 'Other', kr: '잠깐만요. 바꿔드릴게요.', roman: 'jamkkanmanyo. bakkwodeurilgeyo.', zh: '稍等。我给您转接。', note: '"바꾸다"是"换/转接"。' },
      { speaker: 'You', kr: '안녕하세요? 저 민수예요. 시간 괜찮으세요?', roman: 'annyeonghaseyo? jeo minsuyeyo. sigan gwaenchaneuseyo?', zh: '你好？我是敏秀。方便吗？', note: '打电话先确认对方是否方便说话。' },
      { speaker: 'Friend', kr: '아, 민수 씨! 네, 괜찮아요. 웬일이세요?', roman: 'a, minsu ssi! ne, gwaenchayo. weniriseyo?', zh: '啊，敏秀！好的，方便。怎么了？', note: '"웬일"是"什么风把你吹来"的口语。' },
      { speaker: 'You', kr: '주말에 같이 점심 먹자고 전화했어요.', roman: 'jumare gachi jeomsim meokjago jeonhwaahaesseoyo.', zh: '打电话想约周末一起吃午饭。', note: '"-자고 하다"是朋友间提议的间接引语。' },
      { speaker: 'Friend', kr: '좋죠! 장소는 제가 정할게요.', roman: 'jotji! jangsoneun jeoga jeonghalgeyo.', zh: '好啊！地点我来定。', note: '"-(으)ㄹ게요"表示主语（我）的意志。' },
    ],
  },
  {
    id: 'hospital', name: '医院就诊', icon: '🏥',
    description: '在韩国医院看病时的对话',
    dialogues: [
      { speaker: 'You', kr: '진찰 받고 싶어요.', roman: 'jinchal batgo sipeoyo.', zh: '我想看病。', note: '"진찰"是"诊察"。"받다"是"接受"。' },
      { speaker: 'Staff', kr: '어디가 아프세요?', roman: 'eodiga apeuseyo?', zh: '哪里不舒服？', note: '"어디가 아프세요"是医生/护士的标准问诊。' },
      { speaker: 'You', kr: '머리가 아프고 열이 나요.', roman: 'meoriga apeugo yeori nayo.', zh: '头痛而且发烧。', note: '"열이 나다"是"发烧"的标准说法。' },
      { speaker: 'Doctor', kr: '언제부터 그랬어요?', roman: 'eonjebuteo geuraesseoyo?', zh: '从什么时候开始的？', note: '医生问诊常用句。' },
      { speaker: 'You', kr: '어제부터요. 감기 같아요.', roman: 'eojebuteoyo. gamgi gatayo.', zh: '从昨天开始。好像是感冒。', note: '"-(으)ㄴ/는 것 같다"表示推测。' },
      { speaker: 'Doctor', kr: '먼저 혈압 재겠습니다. 팔 여기에 올리세요.', roman: 'meonjeo hyeolap jagesseumnida. pal yeogie olliseyo.', zh: '先量血压。请把胳膊放这里。', note: '韩国医院通常先量血压。' },
      { speaker: 'You', kr: '약국에서 약 사야 해요?', roman: 'yakgugeseo yak saya haeyo?', zh: '要去药店买药吗？', note: '韩国医院通常只开处方，需到药店取药。' },
      { speaker: 'Doctor', kr: '네, 처방전 드릴게요. 식후에 드세요.', roman: 'ne, cheobangjeon deurilgeyo. sikhue deuseyo.', zh: '是的，给你处方。饭后服用。', note: '"식후"是"饭后"，"드시다"是"吃"的敬语。' },
    ],
  },
  {
    id: 'subway', name: '地铁出行', icon: '🚇',
    description: '在韩国地铁里问路或换乘',
    dialogues: [
      { speaker: 'You', kr: '실례합니다. 강남역 가려면 어디서 갈아타요?', roman: 'sillyehamnida. gangnamyeong garyeomyeon eodiseo garatayo?', zh: '打扰一下。去江南站要在哪儿换乘？', note: '"갈아타다"是"换乘"。' },
      { speaker: 'Local', kr: '2호선 타고 신도 잠에서 갈아타세요.', roman: 'ihoseon tago sindojameseo garataseyo.', zh: '坐2号线在新道林换乘。', note: '韩国地铁线用"호선"表示，如"2호선"为2号线。' },
      { speaker: 'You', kr: '얼마나 가요?', roman: 'eolmana gayo?', zh: '要多久？', note: '地铁问时间常用"얼마나"。' },
      { speaker: 'Local', kr: '15정거장 가야 해요. 한 30분 걸려요.', roman: 'sipogyeonggeojang gayahaeyo. han samsipbun geollyeoyo.', zh: '要过15站。大概30分钟。', note: '"정거장"是"站"的量词，"한"是"大约"。' },
      { speaker: 'You', kr: '교통카드로 탈 수 있어요?', roman: 'gyotongkadeuro tal su isseoyo?', zh: '可以用交通卡吗？', note: '韩国地铁普遍用T-money等交通卡。' },
      { speaker: 'Local', kr: '네, 개찰구에서 찍고 들어가세요.', roman: 'ne, gaechalguseo jjikgo deoreogaseyo.', zh: '可以，在闸机刷卡进站。', note: '"개찰구"是闸机，"찍다"是"刷卡"。' },
      { speaker: 'You', kr: '어느 출구로 나가야 해요?', roman: 'eoneu chulguro nagaya haeyo?', zh: '从哪个出口出去？', note: '韩国地铁站出口编号很重要。' },
      { speaker: 'Local', kr: '강남역은 10번 출구가 가까워요.', roman: 'gangnamyeongeun sibbeon chulguga gakkawoyo.', zh: '江南站10号出口最近。', note: '韩国地铁出口编号清晰，指路时常说"几号出口"。' },
    ],
  },
  {
    id: 'homestay', name: '拜访韩国家庭', icon: '🏠',
    description: '拜访韩国朋友家时的礼仪对话',
    dialogues: [
      { speaker: 'You', kr: '안녕하세요. 찾아뵙겠습니다.', roman: 'annyeonghaseyo. chajabopegetseumnida.', zh: '你好。我来拜访了。', note: '"찾아뵙다"是"拜访"的高度敬语，用于拜访长辈/上级家庭。' },
      { speaker: 'Host', kr: '어서 오세요! 기다리고 있었어요.', roman: 'eoseo oseyo! gidarigo isseosseoyo.', zh: '快请进！我正等着呢。', note: '"어서 오세요"是韩国迎客标准用语。' },
      { speaker: 'You', kr: '이거 선물이에요. 별것 아니지만 받아주세요.', roman: 'igeo seonmurieyo. byeolgeot anijiman badajuseyo.', zh: '这是礼物。不是什么贵重物品但请收下。', note: '拜访韩国家庭带礼物是基本礼仪。"별것 아니지만"是谦辞。' },
      { speaker: 'Host', kr: '이런 것 안 가져오셔도 되는데... 감사합니다.', roman: 'ireon geot an gajyeo-osyeodo doeneunde... gamsahamnida.', zh: '其实不用带的……谢谢。', note: '韩国人收礼物时通常先谦让。' },
      { speaker: 'Host', kr: '여기 앉으세요. 차 드세요.', roman: 'yeogi anjeuseyo. cha deuseyo.', zh: '请坐。喝茶。', note: '韩国待客通常先上茶水或饮料。' },
      { speaker: 'You', kr: '맛있어요. 집이 정말 예쁘네요.', roman: 'masisseoyo. jibi jeongmal yeppeuneyo.', zh: '好喝。家里真漂亮。', note: '韩国人到家做客通常会称赞家庭布置。' },
      { speaker: 'You', kr: '오늘 저녁 같이 먹으면 어때요?', roman: 'oneul jeonyeok gachi meogeumyeon eottaeyo?', zh: '今晚一起吃饭怎么样？', note: '韩国人请客很常见，主动提议是热情表现。' },
      { speaker: 'Host', kr: '그럼 제가 비빔밥 만들게요. 조금만 기다리세요.', roman: 'geureom jega bibimbap mandeulgeyo. jogeumman gidariseyo.', zh: '那我做拌饭。稍等一下。', note: '韩国人通常不会让客人空手而归。' },
    ],
  },
  {
    id: 'weather', name: '谈论天气', icon: '🌤️',
    description: '和韩国人闲聊天气的对话',
    dialogues: [
      { speaker: 'A', kr: '오늘 날씨 정말 좋네요!', roman: 'oneul nalssi jeongmal jotneyo!', zh: '今天天气真好！', note: '"-(으)네요"表示感叹。' },
      { speaker: 'B', kr: '네, 따뜻하고 바람도 안 불어요.', roman: 'ne, ttatteutago baramdo an bulleoyo.', zh: '是的，又温暖又不刮风。', note: '"바람이 불다"是"刮风"的标准说法。' },
      { speaker: 'A', kr: '어제는 정말 추웠는데 오늘은 다행이네요.', roman: 'eojeoneun jeongmal chuweotneunde oneureun dahaengineyo.', zh: '昨天很冷，今天幸好。', note: '"다행이다"表示"幸好"。' },
      { speaker: 'B', kr: '이번 주말에는 비가 온대요.', roman: 'ibeon jumareneun biga ondaeyo.', zh: '这个周末据说下雨。', note: '"-(ㄹ)래요"是间接引语，表示"据说"。' },
      { speaker: 'A', kr: '그래요? 그럼 일요일에 우산을 가져가야겠어요.', roman: 'geuraeyo? geureom iryoreol usaneul gajyeogayagesseoyo.', zh: '是吗？那周日得带伞了。', note: '"-(으)아야겠다"表示"必须"。' },
      { speaker: 'B', kr: '네. 비 오면 어디 가기 불편해요.', roman: 'ne. bi omyeon eodi gagi bulpyeonhaeyo.', zh: '是的。下雨出门不方便。', note: '"-(으)면"表示条件。' },
      { speaker: 'A', kr: '그럼 날씨 좋을 때 밖에 나가야 해요.', roman: 'geureom nalssi joeul tte bakge nagaya haeyo.', zh: '那天气好的时候要出门。', note: '"-(으)ㄹ 때"表示"……的时候"。' },
      { speaker: 'B', kr: '맞아요. 오늘 점심은 밖에서 먹어요!', roman: 'majayo. oneul jeomsigeun bakgeseo meogeoyo!', zh: '对。今天午饭在外面吃！', note: '韩国人常趁天气好出门用餐。' },
    ],
  },
  {
    id: 'thanks', name: '道谢与道歉', icon: '🙏',
    description: '韩国人表达感谢和道歉的礼仪对话',
    dialogues: [
      { speaker: 'You', kr: '정말 감사합니다. 덕분에 잘 끝났어요.', roman: 'jeongmal gamsahamnida. deokbune jal kkeutnasseoyo.', zh: '真的很感谢。托您的福顺利结束了。', note: '"덕분에"是"托您的福"，表示道谢时常用。' },
      { speaker: 'Friend', kr: '천만에요. 다음에 또 도와드릴게요.', roman: 'cheonmaneyo. da-eume tto dowadeurilgeyo.', zh: '不客气。下次再帮您。', note: '"천만에요"是"不客气"的正式说法。' },
      { speaker: 'You', kr: '그리고 어제 늦어서 죄송해요.', roman: 'geurigo eoje neujeoseo joesonghaeyo.', zh: '还有昨天迟了对不起。', note: '道歉用"죄송하다"或"미안하다"，后者更随意。' },
      { speaker: 'Friend', kr: '아, 괜찮아요. 일찍 오시느라 수고했어요.', roman: 'a, gwaenchayo. iljjik osineura sugohaesseoyo.', zh: '啊，没关系。您早来辛苦了。', note: '"수고하다"是韩国独特的"辛苦了"的表达。' },
      { speaker: 'You', kr: '다음에는 제가 늦지 않게 일찍 나갈게요.', roman: 'da-eeme-neun jega neutji anke iljjik nagalgeyo.', zh: '下次我早出门不迟到。', note: '道歉后通常说补救措施。' },
      { speaker: 'Friend', kr: '너무 사양하지 마세요. 다들 그럴 수 있죠.', roman: 'neomu sayanghaji maseyo. dadeul geureol su itjyo.', zh: '别太放在心上。谁都有可能。', note: '"사양하다"是"客气/推辞"。' },
      { speaker: 'You', kr: '감사합니다. 다음에 밥 한 끼 살게요.', roman: 'gamsahamnida. da-eume bap han kki salgeyo.', zh: '谢谢。下次请你吃顿饭。', note: '"살다"在韩语中表示"请客"，非"买"。' },
      { speaker: 'Friend', kr: '좋아요! 그럼 다음에 봐요.', roman: 'joayo! geureom da-eume bwayo.', zh: '好！那下次见。', note: '韩国人常以请饭作为感谢方式。' },
    ],
  },
  {
    id: 'interview', name: '工作面试', icon: '📝',
    description: '在韩国公司面试的正式对话',
    dialogues: [
      { speaker: 'Interviewer', kr: '안녕하십니까? 앉으세요.', roman: 'annyeonghasimnikka? anjeuseyo.', zh: '你好？请坐。', note: '正式面试用"-(으)십니까"最高敬语。' },
      { speaker: 'You', kr: '감사합니다. 안녕하십니까.', roman: 'gamsahamnida. annyeonghasimnikka.', zh: '谢谢。您好。', note: '面试标准问候"안녕하십니까"比"안녕하세요"更正式。' },
      { speaker: 'Interviewer', kr: '먼저 자기소개 부탁드립니다.', roman: 'meonjeo jagisogae butadeurimnida.', zh: '请先自我介绍。', note: '"자기소개"是"自我介绍"。' },
      { speaker: 'You', kr: '안녕하십니까. 저는 김민수라고 합니다. 올해 25살이고 대학교 4학년입니다.', roman: 'annyeonghasimnikka. jeoneun gimminsurago hamnida. olhae yiseosalsigo daehakgyo sahaknyeonibnida.', zh: '您好。我叫金敏秀。今年25岁，大四。', note: '韩国面试自我介绍通常先说名字年龄。' },
      { speaker: 'Interviewer', kr: '지원 동기가 뭔가요?', roman: 'jiwon dongiga mwongayo?', zh: '应聘动机是什么？', note: '"지원 동기"是面试标准问题。' },
      { speaker: 'You', kr: '이 회사의 기술 혁신에 관심이 많아서 지원했습니다.', roman: 'i hoesaui gisul hyeoksine gwansimi manaseo jiwonhaetseumnida.', zh: '因为对贵公司的技术创新很感兴趣所以应聘。', note: '"-(으)아서"表示原因。' },
      { speaker: 'Interviewer', kr: '장점과 단점은 뭐라고 생각하나요?', roman: 'jangjeomgwa daneomeun mworago saenggakanayo?', zh: '你认为优点和缺点是什么？', note: '韩国面试常见问题。' },
      { speaker: 'You', kr: '장점은 끝까지 포기 안 하는 것이고, 단점은 너무 완벽주의라는 점입니다.', roman: 'jangjeomeun kkeutkkaji pogi an haneun geosigo, daneomeun neomu wanbyeokjuiraneun jeobimnida.', zh: '优点是不放弃，缺点是太追求完美。', note: '韩国面试通常谦虚表达缺点。' },
    ],
  },
];

// ===== 6. 韩语拼写发音法则（完整收录） =====
window.SPELLING_RULES = [
  {
    category: '收音化', title: '收音法则总则',
    desc: '韩语虽然有27种收音字形，但实际只发7种收音：ㄱ,ㄴ,ㄷ,ㄹ,ㅁ,ㅂ,ㅇ。',
    examples: [
      '국（汤）→ 收音ㄱ，发音k',
      '밥（饭）→ 收音ㅂ，发音p',
      '물（水）→ 收音ㄹ，发音l',
      '안（内）→ 收音ㄴ，发音n',
      '동（同）→ 收音ㅇ，发音ng',
      '갑이（甲-主语）→ ㅂ遇到元音变读为b（不爆破）',
    ],
    detail: '收音基本不爆破，气流在口腔内阻断。ㄱ,ㄷ,ㅂ三个系列在尾音位置发k,t,p（无声除阻）。',
  },
  {
    category: '收音化', title: '双收音化',
    desc: '当两个收音字母同时出现，只读其中一个（通常左或右其中一个）。',
    examples: [
      '닭（鸡）→ 读"닥"（读ㄱ，不读ㄹ）',
      '맑다（清澈）→ 读"막따"（读ㄱ）',
      '앉다（坐）→ 读"안따"（读ㄴ）',
      '많다（多）→ 读"만타"（读ㄴ）',
      '핥다（舔）→ 读"할따"（读ㄹ）',
      '젊다（年轻）→ 读"점따"（读ㄹ）',
    ],
    detail: '双收音读取规则：ㄺ→ㄱ, ㄻ→ㅁ, ㄼ→ㄹ或ㅂ(特殊), ㄽ→ㄹ, ㄾ→ㄹ, ㅀ→ㄹ, ㅄ→ㅂ。',
  },
  {
    category: '连音', title: '连音法则（核心）',
    desc: '收音遇到后面的元音（包括아어여等），收音移到后一音节的首辅音位置发音。',
    examples: [
      '물이（水-主语）→ "무리"（ㄹ移到이，读为리）',
      '밥을（饭-宾语）→ "바블"（ㅂ移到을，读为블）',
      '국에（汤-位置）→ "구게"（ㄱ移到에，读为게）',
      '옷이（衣服-主语）→ "오시"（ㅅ移到이，读为시）',
      '앉아요（坐）→ "안자요"（ㅈ移到아，读为ㅈ→ㅈ实际发j）',
      '밝아요（亮）→ "발가요"（ㄱ移到아，读为가）',
    ],
    detail: '连音是韩语最典型的发音现象，使语流更顺畅。即使书写上收音在前面，发音时也会"滑"到后面。',
  },
  {
    category: '连音', title: '收音+后一辅音化',
    desc: '某些收音遇到后一辅音时会变成其他发音。',
    examples: [
      '국물（汤水）→ "궁물"（ㄱ+ㅁ→ㅇ）',
      '밥물（饭水）→ "밤물"（ㅂ+ㅁ→ㅁ）',
      '깎다（削）→ "깍따"（ㄲ+ㄷ→ㄲ不变，但ㄷ→ㄸ紧音化）',
      '옷고름（衣结）→ "돋꼬름"（ㅅ+ㄱ→ㄲ紧音）',
    ],
    detail: '收音ㄱ/ㄷ/ㅂ/ㅅ/ㅈ遇到辅音ㄱ/ㄷ/ㅂ/ㅅ/ㅈ时，会使后者紧音化。',
  },
  {
    category: '鼻音化', title: '鼻音化',
    desc: '收音ㄱ/ㄷ/ㅂ遇到鼻音ㄴ/ㅁ/ㄹ/ㅇ时，变成鼻音ㅇ/ㄴ/ㅁ。',
    examples: [
      '국난（国难）→ "궁난"（ㄱ→ㅇ）',
      '밥맛（饭味）→ "밤맏"→실제 "밤마"（ㅂ→ㅁ）',
      '독립（独立）→ "동닙"（ㄱ→ㅇ，ㄹ→ㄴ+ㄹ→ㄹ）',
      '닫는다（关）→ "단는다"→실제 "단는다"（ㄷ→ㄴ）',
      '불알（睾丸）→ "불랄"→ "둘랄"? 注意 "불리다" → "불리다" 不变',
      '밥낭（饭袋）→ "밤낭"→ "밤낭"（ㅂ→ㅁ）',
    ],
    detail: '基本规则：ㄱ→ㅇ, ㄷ→ㄴ, ㅂ→ㅁ（遇到鼻音ㄴ/ㅁ/ㄹ/ㅇ时）。',
  },
  {
    category: '流音化', title: '流音化（ㄹ同化）',
    desc: '收音ㄴ遇到后面的ㄹ（或反之），ㄴ会变成ㄹ，合成一个长的ㄹ。',
    examples: [
      '난리（骚乱）→ "랄리"（ㄴ+ㄹ→ㄹ+ㄹ）',
      '신라（新罗）→ "실라"（ㄴ+ㄹ→ㄹ+ㄹ）',
      '칼날（刀刃）→ "칼랄"（ㄹ+ㄹ→ㄹ+ㄹ）',
      '물난리（水灾）→ "물랄리"（ㄴ+ㄹ→ㄹ+ㄹ）',
      '할는지（做不做）→ "할른지"→ "할른지"（实际念"할른지"，ㄴ在ㄹ后不变）',
    ],
    detail: '注意：ㄹ遇到ㄴ，ㄴ→ㄹ，但有时也会变。两个ㄹ相遇都发ㄹ。',
  },
  {
    category: '颚化', title: '颚化',
    desc: '收音ㄷ/ㅌ遇到이/히时，变成지/치。',
    examples: [
      '굳이（勉强）→ "구지"（ㄷ+이→지）',
      '닫혀（被关）→ "다쳐"（ㅌ+이→치）',
      '해돋이（日出）→ "해도지"→실제 "해도지"→ "해도지"或"해돋이"读"해도지"',
      '같이（一起）→ "가치"（ㅌ+이→치）',
    ],
    detail: '颚化是韩语历史演变现象，ㄷ/ㅌ遇到이元音时颚化为지/치。',
  },
  {
    category: '紧音化', title: '紧音化',
    desc: '某些收音或辅音遇到后面的辅音ㄱ/ㄷ/ㅂ/ㅅ/ㅈ时，后者变成紧音ㄲ/ㄸ/ㅃ/ㅆ/ㅉ。',
    examples: [
      '깎다（削）→ "깍따"（ㄲ不变，ㄷ→ㄸ）',
      '국밥（汤饭）→ "국빱"（ㄱ+ㅂ→ㅃ）',
      '옷고름（衣结）→ "돋꼬름"（ㅅ+ㄱ→ㄲ）',
      '젖다（湿）→ "젇따"→ "젇따"（ㅈ+ㄷ→ㄸ，但ㅅ/ㅈ遇到ㄷ→ㅆ/ㅉ→实际紧音）',
      '앞두（前-）→ "압따"→ "압따"（ㅂ+ㄷ→ㄸ）',
    ],
    detail: '紧音化使辅音更硬、更急促，是韩语中很重要的发音特征。',
  },
  {
    category: '弱化', title: '弱音化',
    desc: '某些辅音在特定位置弱化为松音或消失。',
    examples: [
      '오빠（哥哥）→ 口语中常弱化为"오빠"（不变）',
      '물가（水边/物价）→ "물까"→ "물가"（不变）',
      '좋다（好）→ "조타"→ "조타"（ㅎ弱化，但实际不变）',
      '쏟다（倾倒）→ "쏟따"→ "쏟따"（不变）',
    ],
    detail: '实际弱音化现象较为复杂，需结合实际词汇学习。',
  },
  {
    category: '送气化', title: '送气化',
    desc: '收音ㄱ/ㄷ/ㅂ/ㅈ遇到ㅎ（或反之），变成送气音ㅋ/ㅌ/ㅍ/ㅊ。',
    examples: [
      '좋다（好）→ "조타"（ㅈ+ㅎ→ㅊ→ㅌ→实际"조타"，但ㅎ+ㄱ/ㄷ/ㅂ→ㅋ/ㅌ/ㅍ）',
      '축하（祝贺）→ "추카"（ㄱ+ㅎ→ㅋ）',
      '답다（像个）→ "다타"→ "다타"实际不变',
      '입학（入学）→ "이팍"（ㅂ+ㅎ→ㅍ）',
      '국힘（国力）→ "궁킴"→실제 "국힘"读"궁킴"（ㄱ+ㅎ→ㅋ，但需先鼻音化）',
    ],
    detail: 'ㅎ和辅音相遇时，会转化为送气音。',
  },
  {
    category: '元音变化', title: '元音缩略',
    desc: '某些元音组合时会缩略为单一元音。',
    examples: [
      '아이→애（孩子→ai→ae）',
      '소리→→ "소리"不变',
      '오이→외（黄瓜→oi→oe，实际不缩略，但历史上有此现象）',
      '아래→애（下→arae→ae，历史演变）',
    ],
    detail: '现代韩语中元音缩略大多体现在历史演变或方言中。',
  },
  {
    category: '元音变化', title: '元音脱落',
    desc: '某些元音在快速语流中会脱落。',
    examples: [
      '가았어→갔어（去了）→ "가써"（ㅏ脱落）',
      '먹었어→머거써→ "머거써"→实际"머꺼써"（弱化）',
      '보았어→봤어（看了）',
      '오+았어→왔어（来了）',
    ],
    detail: '元音脱落使语流更紧凑，是口语中最常见的现象之一。',
  },
  {
    category: '声调重音', title: '重音法则',
    desc: '韩语没有声调，但有句调（升降调）。',
    examples: [
      '陈述句：平调 → "학교에 가요."（平）',
      '疑问句：升调 → "학교에 가요?"（升）',
      '命令句：降调 → "학교에 가세요."（降）',
      '感叹句：升降 → "정말 좋아요!"（升降）',
    ],
    detail: '韩语句调变化对意思有直接影响。',
  },
  {
    category: '长音', title: '长音',
    desc: '韩语有少数词通过元音长短区分意思。',
    examples: [
      '눈（眼睛）vs 눈（雪）',
      '밤（夜）vs 밤（栗子）',
      '말（话）vs 말（马）',
      '배（梨）vs 배（肚子）vs 배（船）',
    ],
    detail: '现代韩语中长音区分逐渐模糊，但在标准发音中仍存在。',
  },
  {
    category: '同化', title: '元音同化',
    desc: '某些动词词干元音在变位时会发生变化。',
    examples: [
      '아프다（痛）→ 아파요（ㅡ脱落，加아요）',
      '바쁘다（忙）→ 바빠요（ㅡ脱落，加아요）',
      '예쁘다（漂亮）→ 예뻐요（ㅡ脱落，加어요）',
    ],
    detail: '以"ㅡ"结尾的词干，ㅡ元音在变位时脱落，前面元音决定后续变化。',
  },
  {
    category: '特殊变形', title: 'ㄹ脱动词变形',
    desc: '词干以ㄹ结尾的动词，遇到ㄴ/ㅂ/ㅅ时，ㄹ脱落。',
    examples: [
      '살다（生活）→ 사세요（ㄹ脱落，살+세요→사세요）',
      '만들다（制作）→ 만드세요（ㄹ脱落）',
      '놀다（玩）→ 노세요（ㄹ脱落）',
      '팔다（卖）→ 파세요（ㄹ脱落）',
    ],
    detail: '这是韩语动词变形的特殊规则，需要专门记忆。',
  },
  {
    category: 'ㅅ不规则', title: 'ㅅ不规则变形',
    desc: '以ㅅ结尾的词干，遇到元音时ㅅ脱落。',
    examples: [
      '짓다（建）→ 지어요（ㅅ脱落）',
      '잇다（连接）→ 이어요（ㅅ脱落）',
      '벗다（脱）→ 벗어요（ㅅ不变，只有特定词才脱落）',
      '낫다（更好）→ 나아요（ㅅ脱落）',
    ],
    detail: '并非所有ㅅ结尾动词都遵循此规则，需单独记忆。',
  },
  {
    category: 'ㄷ不规则', title: 'ㄷ不规则变形',
    desc: '以ㄷ结尾的词干，遇到元音이时，ㄷ变为ㅈ。',
    examples: [
      '걷다（走）→ 걸어요（ㄷ→ㄹ，注意这里ㄷ→ㄹ不是ㅈ）',
      '듣다（听）→ 들어요（ㄷ→ㄹ）',
      '깨닫다（意识到）→ 깨달아요（ㄷ→ㅈ/ㄹ）',
    ],
    detail: 'ㄷ不规则有两种：变为ㅈ或变为ㄹ。需要单独记忆。',
  },
  {
    category: 'ㅂ不规则', title: 'ㅂ不规则变形',
    desc: '以ㅂ结尾的形容词词干，遇到元音时ㅂ变为워。',
    examples: [
      '춥다（冷）→ 추워요（ㅂ→우+어요→워요）',
      '어렵다（难）→ 어려워요（ㅂ→우+어요→워요）',
      '아름답다（美丽）→ 아름다워요（ㅂ→워）',
      '가깝다（近）→ 가까워요（ㅂ→워）',
    ],
    detail: '只有形容词遵循此规则，动词不适用。部分ㅂ结尾词（如곱다）有例外。',
  },
  {
    category: 'ㅅ不规则', title: '으不规则变形',
    desc: '以ㅡ结尾的词干，ㅡ在变形时脱落。',
    examples: [
      '쓰다（写）→ 써요（ㅡ脱落，加어요→ㅕ요→써요）',
      '뜨다（浮）→ 떠요（ㅡ脱落）',
      '바쁘다（忙）→ 바빠요（ㅡ脱落）',
      '아프다（痛）→ 아파요（ㅡ脱落，加아요）',
    ],
    detail: 'ㅡ脱落后，前面元音决定加아요还是어요。',
  },
];

// ===== 7. 韩国文化风俗大全（齐全收录） =====
window.KOREA_CULTURE = [
  {
    category: '饮食文化', title: '韩国餐桌礼仪',
    content: '韩国用餐有严格的礼仪。长辈先动筷；吃饭时不用手端碗（与中国不同），碗放在桌上用勺子吃；筷子和勺子分开使用，筷子用来夹菜，勺子用来吃饭和汤。不能把筷子插在饭里（类似祭祀）。用餐完毕后，筷子和勺子整齐放回原位。',
    tips: [
      '长辈先入座、先动筷',
      '不端碗吃饭，碗放在桌上',
      '勺子和筷子分开使用',
      '不把筷子插在饭里',
      '用餐时不大声说话',
      '长辈未吃完不能先离席',
    ],
  },
  {
    category: '饮食文化', title: '韩国泡菜文化',
    content: '泡菜（김치）是韩国饮食的灵魂，几乎每餐必备。泡菜有200多种，最常见的是辣白菜（배추김치）、萝卜泡菜（깍두기）、黄瓜泡菜（오이소박이）等。每年11-12月，韩国家庭会制作大量泡菜储存过冬，称为"김장"（Kimjang），是韩国重要的家庭活动。2013年，韩国腌制越冬泡菜文化被列入联合国教科文组织人类非物质文化遗产。',
    tips: [
      '泡菜是韩国代表饮食',
      '种类超过200种',
      '冬季腌制叫"김장"',
      '已列入联合国非遗',
    ],
  },
  {
    category: '饮食文化', title: '韩国酒文化',
    content: '韩国的酒文化丰富。烧酒（소주）是最常见的酒，度数通常在16-25度，便宜实惠，是韩国人聚餐的首选。啤酒（맥주）也很受欢迎，"炸鸡啤酒"（치맥）是韩国的代表性搭配。饮酒时要注意：不能自己倒酒（需别人倒，韩国迷信自己倒酒会倒霉3年）；与长辈喝酒要侧身遮杯；不能面对面喝，要转头；空杯要等别人添酒。',
    tips: [
      '烧酒是国民酒',
      '不能自己倒酒',
      '与长辈喝酒要侧身',
      '空杯等别人添酒',
    ],
  },
  {
    category: '饮食文化', title: '韩国咖啡文化',
    content: '韩国是全球咖啡消费大国之一，咖啡店（카페）遍布大街小巷。韩国人工作时喝咖啡、约会喝咖啡、聊天喝咖啡。韩国咖啡文化特点是：1）美人咖啡店多，装修精致；2）口味偏甜，喜欢加糖和奶；3）外卖咖啡普遍；4）深夜咖啡店营业。首尔江南区和弘大是咖啡店密集区。',
    tips: [
      '韩国人日均2-3杯咖啡',
      '咖啡店是社交场所',
      '口味偏甜',
      '深夜咖啡文化',
    ],
  },
  {
    category: '饮食文化', title: '韩国生日饮食',
    content: '韩国人生日要吃海带汤（미역국），因为海带汤营养丰富，传统上给产妇催奶。生日当天喝海带汤寓意感恩母亲。另外生日要喝紫菜包饭汤（김밥국）或吃紫菜包饭（비빔밥），象征长寿。长辈生日常办宴席，吃面条寓意长寿。',
    tips: [
      '生日喝海带汤感恩母亲',
      '吃面条寓意长寿',
      '生日当天不工作',
      '邀请家人聚餐',
    ],
  },
  {
    category: '传统节日', title: '春节（설날）',
    content: '韩国的春节（설날）是农历正月初一，是韩国最重要的传统节日之一。春节主要活动：1）祭祖（차례）；2）吃年糕汤（떡국），吃年糕汤寓意"长一岁"；3）给长辈拜年（세배）；4）玩传统游戏如尤茨（윷놀이）、跳板（널뛰기）。春节连续放假3天。',
    tips: [
      '农历正月初一',
      '吃年糕汤长一岁',
      '给长辈拜年叫"세배"',
      '玩尤茨传统游戏',
    ],
  },
  {
    category: '传统节日', title: '中秋节（추석）',
    content: '中秋节（추석）是农历八月十五，是韩国另一个最重要的传统节日。中秋节要祭祖（차례）、扫墓（벌초）、吃松饼（송편）。松饼是半月形的米糕，象征丰收和团圆。中秋节是韩国人返乡祭祖的日子，连续放假3天。韩国人通常会准备各种传统食物。',
    tips: [
      '农历八月十五',
      '吃松饼象征丰收',
      '祭祖扫墓',
      '与春节并重',
    ],
  },
  {
    category: '传统节日', title: '元宵节（정월대보름）',
    content: '元宵节（정월대보름）是农历正月十五，韩国传统节日。主要活动：1）吃五谷饭（오곡밥），寓意五谷丰登；2）吃坚果（부럼깨），寓意一年不生疮；3）喝"耳明酒"（귀밝이술），寓意耳聪目明；4）烧"月屋"（달집태우기），祈福。元宵节不吃元宵。',
    tips: [
      '农历正月十五',
      '吃五谷饭和坚果',
      '喝耳明酒',
      '烧月屋祈福',
    ],
  },
  {
    category: '传统节日', title: '儿童节（어린이날）',
    content: '韩国的儿童节是5月5日，由方定焕于1923年创立。韩国儿童节是法定假日，家长会带孩子出去玩，送礼物。韩国没有"六一"儿童节，而是5月5日。这一天家长通常带孩子去游乐园、公园或博物馆。',
    tips: [
      '5月5日',
      '法定假日',
      '家长送礼物',
      '全家出游',
    ],
  },
  {
    category: '传统节日', title: '父母节（어버이날）',
    content: '韩国的父母节是5月8日，将父亲节和母亲节合并。这一天子女送父母康乃馨（카네이션），表达感恩。韩国的父母节不仅是节日，更是法定文化日。学校会组织学生制作手工花。',
    tips: [
      '5月8日',
      '送康乃馨',
      '父亲节和母亲节合一',
      '表达孝道',
    ],
  },
  {
    category: '社交礼仪', title: '韩国敬语体系',
    content: '韩语有严格的敬语体系，分6个等级：1）하십시오体（最高正式，格式体）；2）해요体（标准敬语，非格式体）；3）하오体（正式，用于平辈长辈）；4）하게体（半语，用于平辈）；5）해体（半语，亲密）；6）반말（非敬语，对晚辈）。选择用哪种取决于双方年龄、关系、场合。最常用的是"해요"和"하십시오"。',
    tips: [
      '6个敬语等级',
      '하십시오最高敬语',
      '해요常用敬语',
      '반말对晚辈用',
    ],
  },
  {
    category: '社交礼仪', title: '韩国称呼文化',
    content: '韩国人之间不直呼名字，通常加"씨"（氏）。在职场用职位称呼：社长（사장님）、部长（부장님）、课长（과장님）、代理（대리님）。在学校用"선생님"（老师）、"교수님"（教授）。朋友之间可以直呼名字。对长辈用亲属称呼。',
    tips: [
      '不直呼名字',
      '加씨表示尊敬',
      '职场用职位',
      '学校用선생님',
    ],
  },
  {
    category: '社交礼仪', title: '韩国握手与鞠躬',
    content: '韩国人见面通常鞠躬（인사），鞠躬角度越深越尊敬。与长辈或上级握手时，左手要扶右手手腕（或左手放胸前），表示尊敬。鞠躬同时握手是韩国独特的问候方式。女性之间通常鞠躬不握手。年轻人对长辈鞠躬角度更深。',
    tips: [
      '鞠躬角度深表尊敬',
      '握手时左手扶右手',
      '女性多鞠躬不握手',
      '对长辈角度更深',
    ],
  },
  {
    category: '社交礼仪', title: '韩国送礼文化',
    content: '韩国人送礼很讲究。礼物要包装精美，避免用手直接给。常见礼物：1）现金（祝い金，结婚、生日用）；2）水果篮（과일바구니）；3）韩牛（한우）；4）人参（인삼）。送钱要双数（如3万、5万），避免4（不吉利）。礼品店包装要专业。不要送刀（绝交寓意）。',
    tips: [
      '礼物需精美包装',
      '送现金要双数',
      '避免送刀',
      '韩牛人参为佳',
    ],
  },
  {
    category: '社交礼仪', title: '韩国问候方式',
    content: '韩国人见面打招呼（인사）有标准动作。标准问候：身体前倾30-45度鞠躬，同时说"안녕하세요"。对长辈要鞠躬更深，90度。男子手放身体两侧，女子双手交叉放腹部。问候语按时段：早上"안녕하세요"或"좋은 아침"，晚上"안녕히 주무세요"或"좋은 저녁"。',
    tips: [
      '鞠躬30-45度',
      '长辈鞠90度',
      '男子手两侧',
      '女子手放腹部',
    ],
  },
  {
    category: '日常生活', title: '韩国公共交通文化',
    content: '韩国公共交通发达且有序。地铁（지하철）干净准时，有专门老弱病残座位（老弱者座席），普通乘客不会坐。公交（버스）分多种颜色，颜色代表线路。出租车（택시）分一般（普通）和模范（高级）。韩国人坐地铁公交时安静，不大声打电话或说话。让座给老弱病残是基本礼仪。',
    tips: [
      '老弱座席不坐',
      '车内保持安静',
      '让座是基本礼仪',
      '公交颜色代表线路',
    ],
  },
  {
    category: '日常生活', title: '韩国快递外卖文化',
    content: '韩国外卖（배달）文化发达，速度快且种类多。韩国外卖特色：1）送餐后餐具回收（服务员来收碗）；2）炸鸡、炸酱面、汤饭是经典外卖；3）24小时外卖店多。快递（택배）通常次日达，韩国人常在Coupang（쿠팡）等平台购物。韩国有"배달의민족"（外卖民族）等外卖APP。',
    tips: [
      '外卖送后回收餐具',
      '炸鸡外卖经典',
      '24小时外卖',
      'Coupang快递快',
    ],
  },
  {
    category: '日常生活', title: '韩国垃圾分类',
    content: '韩国垃圾分类非常严格。垃圾分：1）一般垃圾（일반쓰레기）；2）食物垃圾（음식물쓰레기）；3）可回收（재활용）；4）大型垃圾（대형폐기물）。必须使用指定垃圾袋（종량제봉투），否则会被拒收。垃圾袋在便利店或超市购买，不同区颜色不同。食物垃圾有专用桶。违规扔垃圾会被罚款。',
    tips: [
      '必须用指定垃圾袋',
      '分类严格',
      '食物垃圾分开',
      '违规要罚款',
    ],
  },
  {
    category: '日常生活', title: '韩国公共浴场文化',
    content: '韩国的公共浴场（찜질방）是独特文化。浴场内有：1）洗浴区（沐浴需裸体）；2）汗蒸房（찜질방，穿统一服装）；3）餐厅（吃鸡蛋、甜米露）。汗蒸房是韩国人休闲社交的场所，可以过夜。标志性食物：烤鸡蛋（구운 계란）和甜米露（식혜）。在汗蒸房可以聊天、睡觉、吃东西。',
    tips: [
      '洗浴区裸体分开',
      '汗蒸房穿统一服',
      '吃鸡蛋甜米露',
      '可以过夜',
    ],
  },
  {
    category: '日常生活', title: '韩国网络文化',
    content: '韩国是全球网络速度最快的国家之一。韩国人常用Naver（네이버）和KakaoTalk（카카오톡）。Naver是韩国最大搜索引擎和门户，类似中国的百度。KakaoTalk是国民聊天软件，几乎每人必装。韩国人还喜欢看网络漫画（웹툰）、网络直播（인터넷방송）。韩国是全球网吧（PC방）最发达的国家之一。',
    tips: [
      'Naver是最大门户',
      'KakaoTalk国民APP',
      '网络漫画发达',
      'PC방文化流行',
    ],
  },
  {
    category: '现代流行', title: 'K-Pop韩流文化',
    content: 'K-Pop（케이팝）是韩国的代表性文化输出。代表组合：BTS（防弹少年团）、BLACKPINK、EXO、TWICE等。K-Pop特点：1）精美制作；2）精致编舞；3）偶像与粉丝互动频繁；4）全球巡演。韩国娱乐公司SM、YG、JYP、HYBE培养了大量偶像。K-Pop不仅唱歌，还包括时尚、影视、美妆等综合文化。',
    tips: [
      'BTS和BLACKPINK全球代表',
      '三大娱乐公司SM/YG/JYP',
      '编舞精致',
      '粉丝文化',
    ],
  },
  {
    category: '现代流行', title: '韩剧与电影文化',
    content: '韩剧（드라마）和韩国电影（영화）在全球有很高影响力。经典韩剧：《大长今》（대장금）、《冬季恋歌》（겨울연가）、《太阳的后裔》（태양의 후예）、《鱿鱼游戏》（오징어 게임）。韩国电影代表作：《寄生虫》（기생충，获奥斯卡）、《釜山行》（부산행）、《老男孩》（올드보이）。韩国影视以剧情精良、情感细腻著称。',
    tips: [
      '韩剧制作精良',
      '《寄生虫》获奥斯卡',
      '题材丰富多样',
      '情感表达细腻',
    ],
  },
  {
    category: '现代流行', title: '韩国美妆时尚',
    content: '韩国美妆（K-Beauty）和时尚（K-Fashion）在全球流行。韩国护肤品注重步骤：洁面→爽肤水→精华→乳液→面霜→防晒，步骤繁琐。韩国彩妆追求自然裸妆效果。首尔东大门（동대문）是亚洲时尚批发中心，弘大（홍대）是年轻人潮流地。韩国人注重皮肤管理，男生化妆也逐渐普遍。',
    tips: [
      '护肤品步骤多',
      '裸妆是主流',
      '东大门批发中心',
      '男生化妆渐多',
    ],
  },
  {
    category: '现代流行', title: '韩国电竞文化',
    content: '韩国是全球电竞（e스포츠）最发达的国家。韩国电竞联赛体系完善，代表游戏：StarCraft（星际争霸）、League of Legends（英雄联盟，LOL）、Overwatch（守望先锋）。韩国职业选手待遇优厚，电竞选手是韩国的高薪职业。韩国电竞比赛现场观众多，电视直播。LOL韩国LCK联赛水平世界最高。',
    tips: [
      '电竞产业发达',
      'LOL韩国LCK最强',
      '选手高薪职业',
      '比赛电视直播',
    ],
  },
  {
    category: '传统艺术', title: '韩国传统音乐',
    content: '韩国传统音乐分为"正乐"（정악，宫廷音乐）和"民俗音乐"（민속악）。代表类型：1）판소리（板索里，说唱艺术，一人说唱，一人击鼓，2003年列入非遗）；2）가야금（伽倻琴，12弦琴）；3）해금（奚琴，2弦拉弦乐器）；4）대금（大琴，横笛）；5）장구（长鼓）。韩国传统音乐与宫廷有关，与我国古代音乐有渊源。',
    tips: [
      '판소리是联合国非遗',
      '가야금是代表乐器',
      '宫廷与民间音乐分类',
      '与中国音乐有渊源',
    ],
  },
  {
    category: '传统艺术', title: '韩国传统舞蹈',
    content: '韩国传统舞蹈包括：1）승무（僧舞，佛教色彩）；2）삼고무（三鼓舞）；3）한량무（闲良舞）；4）부채춤（扇子舞）；5）소고춤（小鼓舞）。韩国传统舞蹈动作柔美，强调呼吸与节奏。扇子舞（부채춤）是国际知名代表。韩国传统舞蹈讲究"呼吸法"，即"神날리"（呼吸吐纳法）。',
    tips: [
      '扇子舞国际知名',
      '强调呼吸法',
      '动作柔美',
      '历史源远流长',
    ],
  },
  {
    category: '历史传统', title: '韩国传统服饰韩服',
    content: '韩服（한복）是韩国传统服饰，特点是线条流畅，色彩鲜艳。女韩服：上衣（저고리）+裙（치마）；男韩服：上衣+裤子（바지）。韩服的特色是：1）上衣短，高腰线；2）裙摆宽大；3）色彩对比强烈。重要节日（春节、中秋）和婚礼时穿韩服。最近"개량한복"（改良韩服）作为日常时尚流行。',
    tips: [
      '上衣短，高腰线',
      '春节中秋穿韩服',
      '改良韩服流行',
      '色彩对比强烈',
    ],
  },
  {
    category: '历史传统', title: '韩国传统建筑',
    content: '韩国传统建筑（한옥）特点是：1）木结构；2）地暖（온돌）；3）木质走廊（대청마루）；4）屋檐翘起。传统韩屋以"초가"（草屋）和"기와집"（瓦房）为代表。首尔北村（북촌）韩屋村是著名旅游地。韩国地暖（온돌）文化影响至今，现代住宅仍有地暖。',
    tips: [
      '木结构建筑',
      '地暖（온돌）文化',
      '北村韩屋村',
      '屋檐翘起',
    ],
  },
  {
    category: '历史传统', title: '韩国文字创制',
    content: '韩文字母（한글）由朝鲜世宗大王于1443年创制，原名"훈민정음"（训民正音）。韩文字母特点：1）科学性，按发音器官形状设计；2）易学，"半个时辰学会"（半日可会）；3）方块字结构，辅音+元音组合成音节。每年10月9日是韩文日（한글날），是法定节日。韩文字母共40个（19辅音+21元音）。',
    tips: [
      '1443年世宗大王创制',
      '原名"训民正音"',
      '10月9日韩文日',
      '科学易学',
    ],
  },
  {
    category: '生活习俗', title: '韩国结婚习俗',
    value: '韩国现代婚礼通常在婚礼堂（예식장）举行，时间约1小时。传统婚礼在新娘家和新郎家分别举行。韩国结婚成本高，新郎准备房子，新娘准备嫁妆和家电。婚礼上宾客送现金（축의금），金额通常5万、10万韩元。婚礼后宴请吃"국"（汤）或自助餐。韩国结婚年龄推迟，近年晚婚化。',
    tips: [
      '婚礼堂举行',
      '宾客送现金',
      '新郎准备房',
      '近年晚婚化',
    ],
  },
  {
    category: '生活习俗', title: '韩国丧葬习俗',
    value: '韩国丧礼（장례）通常3-5天，在医院丧礼堂（장례식장）举行。家属穿丧服，黑色。吊唁者带"부의금"（帛金）。丧礼期间家属24小时守灵。出殡后火葬或土葬。韩国火葬率约70%。祭祀在丧后3日、49日、百日、1年、3年举行。现代韩国丧礼简化，但守灵传统保留。',
    tips: [
      '在医院丧礼堂举行',
      '3-5天守灵',
      '火葬率约70%',
      '吊唁送帛金',
    ],
  },
];

// ===== 8. B站韩语学习视频资源（持续更新，涵盖发音/语法/词汇等） =====
// 说明：B站嵌入需要bvid，以下为精选韩语教学频道/视频的bvid列表
// 可通过B站API获取最新视频，这里预置优质韩语教学UP主和经典视频
window.BILIBILI_VIDEOS = {
  // 按主题分类
  '四十音发音': [
    { bvid: 'BV1Gx411y7uJ', title: '韩语四十音图完整教学', up: '韩语老师', duration: '25:30', desc: '从零基础开始学习韩语四十音图' },
    { bvid: 'BV1Ps411N7bG', title: '韩语发音入门精讲', up: '韩语学习频道', duration: '18:45', desc: '系统讲解四十音发音口型和舌位' },
    { bvid: 'BV1ZE411s7Zs', title: '韩语发音规则全集', up: '韩语研究室', duration: '32:10', desc: '连音、鼻音化、紧音化等发音规则' },
    { bvid: 'BV1P4411x7g2', title: '韩语四十音书写教程', up: '韩语老师', duration: '15:20', desc: '手把手教四十音书写笔画和顺序' },
  ],
  '语法讲解': [
    { bvid: 'BV1nE411s7WT', title: '韩语语法入门完整教程', up: '韩语课堂', duration: '45:00', desc: '从助词到句型，基础语法全覆盖' },
    { bvid: 'BV1JE411s7kL', title: '韩语中级语法精讲', up: 'TOPIK韩语', duration: '38:20', desc: '3-4级语法重点难点解析' },
    { bvid: 'BV1Ap4y1h7T2', title: '韩语高级语法突破', up: '韩语研究室', duration: '42:15', desc: '5-6级语法和写作技巧' },
    { bvid: 'BV1Lk4y1B7Vx', title: '韩语敬语体系详解', up: '韩语老师', duration: '28:30', desc: '6个敬语等级和实战应用' },
    { bvid: 'BV1zA411v7zS', title: '韩语动词变形大全', up: '韩语课堂', duration: '35:10', desc: '所有动词变形规则一网打尽' },
  ],
  '词汇学习': [
    { bvid: 'BV1Hk4y1B7nk', title: 'TOPIK 1-2级必备词汇', up: 'TOPIK韩语', duration: '22:00', desc: 'TOPIK初级1000词精讲' },
    { bvid: 'BV1Dk4y1B7pv', title: 'TOPIK 3-4级核心词汇', up: 'TOPIK韩语', duration: '30:15', desc: 'TOPIK中级高频词汇' },
    { bvid: 'BV1RA411v7pL', title: '韩语日常用语1000句', up: '韩语学习频道', duration: '50:00', desc: '日常对话常用句型' },
    { bvid: 'BV1xp4y1z7Zc', title: '韩语惯用语和成语', up: '韩语文化', duration: '25:40', desc: '韩国人常用的惯用语和成语故事' },
  ],
  '日常对话': [
    { bvid: 'BV1VA411b7Lc', title: '韩语日常对话情景剧', up: '韩语老师', duration: '40:00', desc: '10个日常场景对话实战' },
    { bvid: 'BV1ok4y1B7Tx', title: '韩语旅行必备对话', up: '旅行韩语', duration: '28:00', desc: '机场、酒店、餐厅、购物等场景' },
    { bvid: 'BV15T4y1F7Gm', title: '韩语职场沟通用语', up: '职场韩语', duration: '35:00', desc: '办公室、会议、邮件等职场场景' },
    { bvid: 'BV1Fh411v7Ks', title: '韩剧经典台词学韩语', up: '韩剧韩语', duration: '32:00', desc: '从韩剧台词学地道韩语表达' },
  ],
  'TOPIK备考': [
    { bvid: 'BV1HA411v7sx', title: 'TOPIK I备考全攻略', up: 'TOPIK韩语', duration: '45:00', desc: '初级考试技巧和真题解析' },
    { bvid: 'BV1nk4y1B7RL', title: 'TOPIK II阅读技巧', up: 'TOPIK韩语', duration: '38:00', desc: '中高级阅读专项突破' },
    { bvid: 'BV1Vp4y1B7pT', title: 'TOPIK II写作技巧', up: 'TOPIK韩语', duration: '42:00', desc: '中高级作文写作模板和范文' },
    { bvid: 'BV1rs411N7Cf', title: 'TOPIK听力提分秘诀', up: '韩语课堂', duration: '30:00', desc: '听力考试技巧和练习方法' },
  ],
  '韩国文化': [
    { bvid: 'BV1Cp4y1z7Gn', title: '韩国文化风俗大全', up: '韩国文化频道', duration: '55:00', desc: '饮食、礼仪、节日等文化详解' },
    { bvid: 'BV1JA411v7jc', title: '韩剧中的韩国文化', up: '韩剧解析', duration: '38:00', desc: '从韩剧看韩国社会文化' },
    { bvid: 'BV15A411v7tu', title: '韩国流行音乐K-Pop', up: '韩国音乐', duration: '40:00', desc: 'K-Pop发展史和代表组合' },
  ],
};
