// ============================================================
// 韩语学习工作台 - 完整数据集
// 数据来源参考：标准韩国语教材、TOPIK考级大纲、u校园韩语学习书籍
// ============================================================

// ===== 1. 韩语四十音图（含发音说明，参考标准教辅） =====
// 19个辅音 + 21个元音 = 40音
window.HANGUL_CONSONANTS = [
  // 基本辅音
  { char: 'ㄱ', roman: 'g/k', sound: 'ㄱ（基：k松音）', desc: '舌根抵住软腭，松开气流。类似汉语g，但力度更轻。位于词首发k，词中发g。', type: 'consonant', order: 1 },
  { char: 'ㄴ', roman: 'n', sound: 'ㄴ（基：n鼻音）', desc: '舌尖抵住上齿龈，气流从鼻腔出。与汉语n相同。', type: 'consonant', order: 2 },
  { char: 'ㄷ', roman: 'd/t', sound: 'ㄷ（基：t松音）', desc: '舌尖抵住上齿龈，突然松开。词首发t，词中发d。', type: 'consonant', order: 3 },
  { char: 'ㄹ', roman: 'r/l', sound: 'ㄹ（基：r/l闪音）', desc: '舌尖轻弹上齿龈。词首发r，词尾发l。汉语无对应，介于r和l之间。', type: 'consonant', order: 4 },
  { char: 'ㅁ', roman: 'm', sound: 'ㅁ（基：m鼻音）', desc: '双唇闭合，气流从鼻腔出。与汉语m相同。', type: 'consonant', order: 5 },
  { char: 'ㅂ', roman: 'b/p', sound: 'ㅂ（基：p松音）', desc: '双唇闭合，突然松开。词首发p，词中发b。', type: 'consonant', order: 6 },
  { char: 'ㅅ', roman: 's', sound: 'ㅅ（基：s松音）', desc: '舌尖靠近上齿龈，气流摩擦而出。与汉语s相似。', type: 'consonant', order: 7 },
  { char: 'ㅇ', roman: 'ng/(无声)', sound: 'ㅇ（基：词首无声/词尾ng）', desc: '位于音节首时不发音（占位），位于音节尾（收音）时发ng。', type: 'consonant', order: 8 },
  { char: 'ㅈ', roman: 'j/ch', sound: 'ㅈ（基：ch松音）', desc: '舌尖抵住下齿龈，舌面靠近硬腭。词首发ch，词中发j。', type: 'consonant', order: 9 },
  { char: 'ㅊ', roman: 'ch', sound: 'ㅊ（送：ch送气音）', desc: '与ㅈ发音部位相同，但送气强烈。类似汉语ch。', type: 'consonant', order: 10 },
  { char: 'ㅋ', roman: 'k', sound: 'ㅋ（送：k送气音）', desc: '与ㄱ相同部位，但送气强烈。类似汉语k。', type: 'consonant', order: 11 },
  { char: 'ㅌ', roman: 't', sound: 'ㅌ（送：t送气音）', desc: '与ㄷ相同部位，但送气强烈。类似汉语t。', type: 'consonant', order: 12 },
  { char: 'ㅍ', roman: 'p', sound: 'ㅍ（送：p送气音）', desc: '与ㅂ相同部位，但送气强烈。类似汉语p。', type: 'consonant', order: 13 },
  { char: 'ㅎ', roman: 'h', sound: 'ㅎ（送：h送气音）', desc: '气流从喉部摩擦而出。与汉语h相似，但更轻。', type: 'consonant', order: 14 },
  // 紧音
  { char: 'ㄲ', roman: 'kk', sound: 'ㄲ（紧：kk紧音）', desc: '与ㄱ相同部位，但声门紧闭，气流受阻。发音硬而急。', type: 'consonant', order: 15 },
  { char: 'ㄸ', roman: 'tt', sound: 'ㄸ（紧：tt紧音）', desc: '与ㄷ相同部位，但声门紧闭。发音硬而急。', type: 'consonant', order: 16 },
  { char: 'ㅃ', roman: 'pp', sound: 'ㅃ（紧：pp紧音）', desc: '与ㅂ相同部位，但声门紧闭。发音硬而急。', type: 'consonant', order: 17 },
  { char: 'ㅆ', roman: 'ss', sound: 'ㅆ（紧：ss紧音）', desc: '与ㅅ相同部位，但声门紧闭。发音硬而急。', type: 'consonant', order: 18 },
  { char: 'ㅉ', roman: 'jj', sound: 'ㅉ（紧：jj紧音）', desc: '与ㅈ相同部位，但声门紧闭。发音硬而急。', type: 'consonant', order: 19 },
];

window.HANGUL_VOWELS = [
  // 基本元音
  { char: 'ㅏ', roman: 'a', sound: 'ㅏ（a）', desc: '口自然张开，舌头自然放下。类似汉语a。', type: 'vowel', order: 20 },
  { char: 'ㅑ', roman: 'ya', sound: 'ㅑ（ya）', desc: '在ㅏ的基础上加y音。类似汉语ya。', type: 'vowel', order: 21 },
  { char: 'ㅓ', roman: 'eo', sound: 'ㅓ（eo）', desc: '口半开，舌身后缩。汉语无对应，介于o和e之间。', type: 'vowel', order: 22 },
  { char: 'ㅕ', roman: 'yeo', sound: 'ㅕ（yeo）', desc: '在ㅓ的基础上加y音。', type: 'vowel', order: 23 },
  { char: 'ㅗ', roman: 'o', sound: 'ㅗ（o）', desc: '口半开，双唇拢圆。类似汉语o。', type: 'vowel', order: 24 },
  { char: 'ㅛ', roman: 'yo', sound: 'ㅛ（yo）', desc: '在ㅗ的基础上加y音。类似汉语yo。', type: 'vowel', order: 25 },
  { char: 'ㅜ', roman: 'u', sound: 'ㅜ（u）', desc: '口半开，双唇拢圆向前。类似汉语u。', type: 'vowel', order: 26 },
  { char: 'ㅠ', roman: 'yu', sound: 'ㅠ（yu）', desc: '在ㅜ的基础上加y音。类似汉语yu。', type: 'vowel', order: 27 },
  { char: 'ㅡ', roman: 'eu', sound: 'ㅡ（eu）', desc: '口微开，舌身平放。汉语无对应，介于i和u之间。', type: 'vowel', order: 28 },
  { char: 'ㅣ', roman: 'i', sound: 'ㅣ（i）', desc: '口微开，嘴角向两边拉开。类似汉语i。', type: 'vowel', order: 29 },
  // 复合元音
  { char: 'ㅐ', roman: 'ae', sound: 'ㅐ（ae）', desc: '口比ㅏ稍小。类似汉语ai。', type: 'vowel', order: 30 },
  { char: 'ㅒ', roman: 'yae', sound: 'ㅒ（yae）', desc: '在ㅐ基础上加y音。', type: 'vowel', order: 31 },
  { char: 'ㅔ', roman: 'e', sound: 'ㅔ（e）', desc: '口比ㅓ稍小。与ㅐ发音相近。', type: 'vowel', order: 32 },
  { char: 'ㅖ', roman: 'ye', sound: 'ㅖ（ye）', desc: '在ㅔ基础上加y音。', type: 'vowel', order: 33 },
  { char: 'ㅘ', roman: 'wa', sound: 'ㅘ（wa）', desc: 'ㅗ+ㅏ复合。类似汉语wa。', type: 'vowel', order: 34 },
  { char: 'ㅙ', roman: 'wae', sound: 'ㅙ（wae）', desc: 'ㅗ+ㅐ复合。类似汉语wai。', type: 'vowel', order: 35 },
  { char: 'ㅚ', roman: 'oe', sound: 'ㅚ（oe）', desc: 'ㅗ+ㅣ复合。类似汉语wei。', type: 'vowel', order: 36 },
  { char: 'ㅝ', roman: 'wo', sound: 'ㅝ（wo）', desc: 'ㅜ+ㅓ复合。类似汉语wo。', type: 'vowel', order: 37 },
  { char: 'ㅞ', roman: 'we', sound: 'ㅞ（we）', desc: 'ㅜ+ㅔ复合。类似汉语wei。', type: 'vowel', order: 38 },
  { char: 'ㅟ', roman: 'wi', sound: 'ㅟ（wi）', desc: 'ㅜ+ㅣ复合。类似汉语wei。', type: 'vowel', order: 39 },
  { char: 'ㅢ', roman: 'ui', sound: 'ㅢ（ui）', desc: 'ㅡ+ㅣ复合。实际中常发e或i音。', type: 'vowel', order: 40 },
];

window.HANGUL_ALL = window.HANGUL_CONSONANTS.concat(window.HANGUL_VOWELS);

// 收音（韵尾）- 27种收音实际发音为7种
window.HANGUL_BATCHIM = [
  { repr: 'ㄱ', sound: 'k', chars: 'ㄱ,ㅋ,ㄲ,ㄳ,ㄺ', desc: '收音ㄱ系列，发k音（不发g）' },
  { repr: 'ㄴ', sound: 'n', chars: 'ㄴ,ㄵ,ㄶ', desc: '收音ㄴ系列，发n音' },
  { repr: 'ㄷ', sound: 't', chars: 'ㄷ,ㅅ,ㅈ,ㅊ,ㅌ,ㅆ,ㅎ', desc: '收音ㄷ系列，发t音（不爆破）' },
  { repr: 'ㄹ', sound: 'l', chars: 'ㄹ,ㄼ,ㄽ,ㄾ,ㅀ', desc: '收音ㄹ系列，发l音' },
  { repr: 'ㅁ', sound: 'm', chars: 'ㅁ,ㄻ,ㄿ', desc: '收音ㅁ系列，发m音' },
  { repr: 'ㅂ', sound: 'p', chars: 'ㅂ,ㅍ,ㅄ,ㄿ,ㄼ', desc: '收音ㅂ系列，发p音（不爆破）' },
  { repr: 'ㅇ', sound: 'ng', chars: 'ㅇ', desc: '收音ㅇ，发ng音' },
];

// ===== 2. TOPIK考级词汇（1-6级，每级丰富收录） =====
window.TOPIK_VOCAB = {
  // TOPIK 1级 - 基础词汇
  1: [
    { word: '안녕하세요', roman: 'annyeonghaseyo', meaning: '你好', pos: '感叹词', example: '안녕하세요, 만나서 반갑습니다.' },
    { word: '감사합니다', roman: 'gamsahamnida', meaning: '谢谢', pos: '感叹词', example: '도와주셔서 감사합니다.' },
    { word: '죄송합니다', roman: 'joesonghamnida', meaning: '对不起', pos: '感叹词', example: '늦어서 죄송합니다.' },
    { word: '네', roman: 'ne', meaning: '是/好的', pos: '感叹词', example: '네, 알겠습니다.' },
    { word: '아니요', roman: 'aniyo', meaning: '不是', pos: '感叹词', example: '아니요, 괜찮습니다.' },
    { word: '이름', roman: 'ireum', meaning: '名字', pos: '名词', example: '이름이 뭐예요?' },
    { word: '학생', roman: 'haksaeng', meaning: '学生', pos: '名词', example: '저는 학생이에요.' },
    { word: '선생님', roman: 'seonsaengnim', meaning: '老师', pos: '名词', example: '선생님, 안녕하세요.' },
    { word: '친구', roman: 'chingu', meaning: '朋友', pos: '名词', example: '친구를 만나요.' },
    { word: '학교', roman: 'hakgyo', meaning: '学校', pos: '名词', example: '학교에 가요.' },
    { word: '집', roman: 'jip', meaning: '家', pos: '名词', example: '집에 있어요.' },
    { word: '물', roman: 'mul', meaning: '水', pos: '名词', example: '물을 마셔요.' },
    { word: '밥', roman: 'bap', meaning: '饭', pos: '名词', example: '밥을 먹어요.' },
    { word: '책', roman: 'chaek', meaning: '书', pos: '名词', example: '책을 읽어요.' },
    { word: '시간', roman: 'sigan', meaning: '时间', pos: '名词', example: '시간이 없어요.' },
    { word: '오늘', roman: 'oneul', meaning: '今天', pos: '名词', example: '오늘 날씨가 좋아요.' },
    { word: '내일', roman: 'naeil', meaning: '明天', pos: '名词', example: '내일 만나요.' },
    { word: '어제', roman: 'eoje', meaning: '昨天', pos: '名词', example: '어제 영화를 봤어요.' },
    { word: '사람', roman: 'saram', meaning: '人', pos: '名词', example: '좋은 사람이에요.' },
    { word: '남자', roman: 'namja', meaning: '男人', pos: '名词', example: '저 남자는 누구예요?' },
    { word: '여자', roman: 'yeoja', meaning: '女人', pos: '名词', example: '그 여자는 예뻐요.' },
    { word: '아이', roman: 'ai', meaning: '孩子', pos: '名词', example: '아이가 귀여워요.' },
    { word: '가족', roman: 'gajok', meaning: '家庭', pos: '名词', example: '가족이 4명이에요.' },
    { word: '아버지', roman: 'abeoji', meaning: '父亲', pos: '名词', example: '아버지는 회사원이에요.' },
    { word: '어머니', roman: 'eomeoni', meaning: '母亲', pos: '名词', example: '어머니는 선생님이에요.' },
    { word: '형', roman: 'hyeong', meaning: '哥哥(男称)', pos: '名词', example: '형이 한 명 있어요.' },
    { word: '오빠', roman: 'oppa', meaning: '哥哥(女称)', pos: '名词', example: '오빠는 의사예요.' },
    { word: '누나', roman: 'nuna', meaning: '姐姐(男称)', pos: '名词', example: '누나는 대학생이에요.' },
    { word: '언니', roman: 'eonni', meaning: '姐姐(女称)', pos: '名词', example: '언니랑 쇼핑해요.' },
    { word: '동생', roman: 'dongsaeng', meaning: '弟弟/妹妹', pos: '名词', example: '동생이 있어요.' },
    { word: '가다', roman: 'gada', meaning: '去', pos: '动词', example: '학교에 가요.' },
    { word: '오다', roman: 'oda', meaning: '来', pos: '动词', example: '친구가 와요.' },
    { word: '먹다', roman: 'meokda', meaning: '吃', pos: '动词', example: '밥을 먹어요.' },
    { word: '마시다', roman: 'masida', meaning: '喝', pos: '动词', example: '커피를 마셔요.' },
    { word: '보다', roman: 'boda', meaning: '看', pos: '动词', example: 'TV를 봐요.' },
    { word: '듣다', roman: 'deutda', meaning: '听', pos: '动词', example: '음악을 들어요.' },
    { word: '읽다', roman: 'ilkda', meaning: '读', pos: '动词', example: '책을 읽어요.' },
    { word: '쓰다', roman: 'sseuda', meaning: '写', pos: '动词', example: '편지를 써요.' },
    { word: '사다', roman: 'sada', meaning: '买', pos: '动词', example: '옷을 사요.' },
    { word: '만나다', roman: 'mannada', meaning: '见', pos: '动词', example: '친구를 만나요.' },
    { word: '좋다', roman: 'jota', meaning: '好', pos: '形容词', example: '날씨가 좋아요.' },
    { word: '나쁘다', roman: 'nappeuda', meaning: '坏', pos: '形容词', example: '날씨가 나빠요.' },
    { word: '크다', roman: 'keuda', meaning: '大', pos: '形容词', example: '방이 커요.' },
    { word: '작다', roman: 'jakda', meaning: '小', pos: '形容词', example: '강아지가 작아요.' },
    { word: '많다', roman: 'manta', meaning: '多', pos: '形容词', example: '사람이 많아요.' },
    { word: '적다', roman: 'jeokda', meaning: '少', pos: '形容词', example: '돈이 적어요.' },
    { word: '예쁘다', roman: 'yeppeuda', meaning: '漂亮', pos: '形容词', example: '꽃이 예뻐요.' },
    { word: '맛있다', roman: 'masitda', meaning: '好吃', pos: '形容词', example: '김치가 맛있어요.' },
    { word: '재미있다', roman: 'jaemiitda', meaning: '有趣', pos: '形容词', example: '영화가 재미있어요.' },
    { word: '사랑하다', roman: 'saranghada', meaning: '爱', pos: '动词', example: '가족을 사랑해요.' },
    { word: '공부하다', roman: 'gongbuhada', meaning: '学习', pos: '动词', example: '한국어를 공부해요.' },
    { word: '운동하다', roman: 'undonghada', meaning: '运动', pos: '动词', example: '매일 운동해요.' },
  ],
  // TOPIK 2级 - 基础进阶
  2: [
    { word: '출발하다', roman: 'chulbalhada', meaning: '出发', pos: '动词', example: '내일 출발해요.' },
    { word: '도착하다', roman: 'dochakhada', meaning: '到达', pos: '动词', example: '공항에 도착했어요.' },
    { word: '예약하다', roman: 'yeyakhada', meaning: '预约', pos: '动词', example: '호텔을 예약했어요.' },
    { word: '주문하다', roman: 'jumunhada', meaning: '点餐/订购', pos: '动词', example: '피자를 주문해요.' },
    { word: '약속', roman: 'yaksok', meaning: '约定/约会', pos: '名词', example: '약속이 있어요.' },
    { word: '약속하다', roman: 'yaksokhada', meaning: '约定', pos: '动词', example: '친구와 약속했어요.' },
    { word: '계획', roman: 'gyehoek', meaning: '计划', pos: '名词', example: '여행 계획을 세워요.' },
    { word: '준비', roman: 'junbi', meaning: '准备', pos: '名词', example: '시험 준비를 해요.' },
    { word: '준비하다', roman: 'junbihada', meaning: '准备', pos: '动词', example: '음식을 준비해요.' },
    { word: '기억', roman: 'gieok', meaning: '记忆', pos: '名词', example: '좋은 기억이에요.' },
    { word: '기억하다', roman: 'gieokhada', meaning: '记住', pos: '动词', example: '이름을 기억해요.' },
    { word: '잊다', roman: 'itda', meaning: '忘记', pos: '动词', example: '약속을 잊었어요.' },
    { word: '걱정', roman: 'geokjeong', meaning: '担心', pos: '名词', example: '걱정하지 마세요.' },
    { word: '걱정하다', roman: 'geokjeonghada', meaning: '担心', pos: '动词', example: '부모님이 걱정해요.' },
    { word: '행복하다', roman: 'haengbokhada', meaning: '幸福', pos: '形容词', example: '정말 행복해요.' },
    { word: '슬프다', roman: 'seulpeuda', meaning: '悲伤', pos: '形容词', example: '영화가 슬퍼요.' },
    { word: '화나다', roman: 'hwanada', meaning: '生气', pos: '形容词', example: '친구한테 화났어요.' },
    { word: '기쁘다', roman: 'gippeuda', meaning: '高兴', pos: '形容词', example: '선물을 받아서 기뻐요.' },
    { word: '피곤하다', roman: 'pigonhada', meaning: '疲劳', pos: '形容词', example: '너무 피곤해요.' },
    { word: '건강하다', roman: 'geonganghada', meaning: '健康', pos: '形容词', example: '할아버지가 건강하세요.' },
    { word: '아프다', roman: 'apeuda', meaning: '疼/生病', pos: '形容词', example: '머리가 아파요.' },
    { word: '병원', roman: 'byeongwon', meaning: '医院', pos: '名词', example: '병원에 가요.' },
    { word: '약', roman: 'yak', meaning: '药', pos: '名词', example: '약을 먹어요.' },
    { word: '감기', roman: 'gamgi', meaning: '感冒', pos: '名词', example: '감기에 걸렸어요.' },
    { word: '약국', roman: 'yakguk', meaning: '药店', pos: '名词', example: '약국에서 약을 사요.' },
    { word: '은행', roman: 'eunhaeng', meaning: '银行', pos: '名词', example: '은행에서 돈을 찾아요.' },
    { word: '돈', roman: 'don', meaning: '钱', pos: '名词', example: '돈이 필요해요.' },
    { word: '계산하다', roman: 'gyesanada', meaning: '结账/计算', pos: '动词', example: '계산해 주세요.' },
    { word: '환전하다', roman: 'hwanjeonhada', meaning: '换钱', pos: '动词', example: '달러를 원으로 환전해요.' },
    { word: '지갑', roman: 'jigap', meaning: '钱包', pos: '名词', example: '지갑을 잃어버렸어요.' },
    { word: '교통카드', roman: 'gyotongkadeu', meaning: '交通卡', pos: '名词', example: '교통카드를 충전해요.' },
    { word: '지하철', roman: 'jihacheol', meaning: '地铁', pos: '名词', example: '지하철을 타요.' },
    { word: '버스', roman: 'beoseu', meaning: '公交车', pos: '名词', example: '버스를 기다려요.' },
    { word: '택시', roman: 'taeksi', meaning: '出租车', pos: '名词', example: '택시를 타요.' },
    { word: '기차', roman: 'gicha', meaning: '火车', pos: '名词', example: '기차로 서울에 가요.' },
    { word: '비행기', roman: 'bihaenggi', meaning: '飞机', pos: '名词', example: '비행기표를 샀어요.' },
    { word: '공항', roman: 'gonghang', meaning: '机场', pos: '名词', example: '공항에 일찍 가요.' },
    { word: '여행', roman: 'yeohaeng', meaning: '旅行', pos: '名词', example: '제주도로 여행가요.' },
    { word: '관광', roman: 'gwangwang', meaning: '观光', pos: '名词', example: '서울을 관광해요.' },
    { word: '호텔', roman: 'hotel', meaning: '酒店', pos: '名词', example: '호텔에 묵어요.' },
    { word: '예약', roman: 'yeyak', meaning: '预约', pos: '名词', example: '예약을 확인해 주세요.' },
    { word: '방', roman: 'bang', meaning: '房间', pos: '名词', example: '방이 깨끗해요.' },
    { word: '열쇠', roman: 'yeolsoe', meaning: '钥匙', pos: '名词', example: '열쇠를 잃어버렸어요.' },
    { word: '프론트', roman: 'peuronteu', meaning: '前台', pos: '名词', example: '프론트에 전화해요.' },
    { word: '식당', roman: 'sikdang', meaning: '餐厅', pos: '名词', example: '식당에서 밥을 먹어요.' },
    { word: '메뉴', roman: 'menyu', meaning: '菜单', pos: '名词', example: '메뉴를 보여주세요.' },
    { word: '맛', roman: 'mat', meaning: '味道', pos: '名词', example: '맛이 아주 좋아요.' },
    { word: '배달', roman: 'baedal', meaning: '外卖/配送', pos: '名词', example: '배달 시켜요.' },
    { word: '포장', roman: 'pojang', meaning: '打包', pos: '名词', example: '포장해 주세요.' },
    { word: '매워요', roman: 'maewoyo', meaning: '辣', pos: '形容词', example: '떡볶이가 매워요.' },
    { word: '달아요', roman: 'darayo', meaning: '甜', pos: '形容词', example: '케이크가 달아요.' },
  ],
  // TOPIK 3级 - 中级
  3: [
    { word: '경험', roman: 'gyeongheom', meaning: '经验', pos: '名词', example: '다양한 경험을 했어요.' },
    { word: '경험하다', roman: 'gyeongheomhada', meaning: '经历', pos: '动词', example: '어려움을 경험했어요.' },
    { word: '노력하다', roman: 'noryeokhada', meaning: '努力', pos: '动词', example: '열심히 노력해요.' },
    { word: '성공하다', roman: 'seonggonghada', meaning: '成功', pos: '动词', example: '시험에 성공했어요.' },
    { word: '실패하다', roman: 'silpaehada', meaning: '失败', pos: '动词', example: '사업에 실패했어요.' },
    { word: '도전하다', roman: 'dojeonhada', meaning: '挑战', pos: '动词', example: '새로운 일에 도전해요.' },
    { word: '발전하다', roman: 'baljeonhada', meaning: '发展', pos: '动词', example: '기술이 발전해요.' },
    { word: '향상되다', roman: 'hyangsangdoeda', meaning: '提高', pos: '动词', example: '실력이 향상됐어요.' },
    { word: '개선하다', roman: 'gaeseonhada', meaning: '改善', pos: '动词', example: '환경을 개선해요.' },
    { word: '해결하다', roman: 'haegyeolhada', meaning: '解决', pos: '动词', example: '문제를 해결해요.' },
    { word: '발견하다', roman: 'balgyeonhada', meaning: '发现', pos: '动词', example: '새로운 사실을 발견했어요.' },
    { word: '연구하다', roman: 'yeonguhada', meaning: '研究', pos: '动词', example: '과학자가 연구해요.' },
    { word: '조사하다', roman: 'josahada', meaning: '调查', pos: '动词', example: '시장을 조사해요.' },
    { word: '분석하다', roman: 'bunseokhada', meaning: '分析', pos: '动词', example: '데이터를 분석해요.' },
    { word: '설명하다', roman: 'seolmyeonghada', meaning: '说明', pos: '动词', example: '이유를 설명해요.' },
    { word: '표현하다', roman: 'pyohyeonhada', meaning: '表达', pos: '动词', example: '감정을 표현해요.' },
    { word: '예상하다', roman: 'yesanghada', meaning: '预料', pos: '动词', example: '결과를 예상했어요.' },
    { word: '결정하다', roman: 'gyeoljeonghada', meaning: '决定', pos: '动词', example: '진로를 결정해요.' },
    { word: '선택하다', roman: 'seontaekhada', meaning: '选择', pos: '动词', example: '직업을 선택해요.' },
    { word: '포기하다', roman: 'pogihada', meaning: '放弃', pos: '动词', example: '꿈을 포기하지 마세요.' },
    { word: '기대하다', roman: 'gidaehada', meaning: '期待', pos: '动词', example: '결과를 기대해요.' },
    { word: '요구하다', roman: 'yoguhada', meaning: '要求', pos: '动词', example: '조건을 요구해요.' },
    { word: '제안하다', roman: 'je'anada', meaning: '建议', pos: '动词', example: '새로운 방안을 제안해요.' },
    { word: '주장하다', roman: 'jujanghada', meaning: '主张', pos: '动词', example: '의견을 주장해요.' },
    { word: '인정하다', roman: 'injeonghada', meaning: '承认', pos: '动词', example: '실수를 인정해요.' },
    { word: '거절하다', roman: 'geojeolhada', meaning: '拒绝', pos: '动词', example: '제안을 거절했어요.' },
    { word: '동의하다', roman: 'dong'uihada', meaning: '同意', pos: '动词', example: '의견에 동의해요.' },
    { word: '반대하다', roman: 'bandaehada', meaning: '反对', pos: '动词', example: '계획에 반대해요.' },
    { word: '응원하다', roman: 'eungwonhada', meaning: '支持/声援', pos: '动词', example: '팀을 응원해요.' },
    { word: '축하하다', roman: 'chukahada', meaning: '祝贺', pos: '动词', example: '생일을 축하해요.' },
    { word: '감동하다', roman: 'gamdonghada', meaning: '感动', pos: '动词', example: '영화에 감동했어요.' },
    { word: '실망하다', roman: 'silmanghada', meaning: '失望', pos: '动词', example: '결과에 실망했어요.' },
    { word: '후회하다', roman: 'huhoehada', meaning: '后悔', pos: '动词', example: '선택을 후회해요.' },
    { word: '걱정스럽다', roman: 'geokjeongseureopda', meaning: '令人担心', pos: '形容词', example: '건강이 걱정스러워요.' },
    { word: '다행이다', roman: 'dahaeng'ida', meaning: '幸好', pos: '形容词', example: '비가 와서 다행이에요.' },
    { word: '당연하다', roman: 'dang'yeonhada', meaning: '当然', pos: '形容词', example: '그건 당연해요.' },
    { word: '확실하다', roman: 'hwaksilhada', meaning: '确实', pos: '形容词', example: '확실한 정보예요.' },
    { word: '불확실하다', roman: 'bulhwaksilhada', meaning: '不确定', pos: '形容词', example: '미래는 불확실해요.' },
    { word: '편리하다', roman: 'pyeollihada', meaning: '便利', pos: '形容词', example: '교통이 편리해요.' },
    { word: '불편하다', roman: 'bulpyeonhada', meaning: '不方便', pos: '形容词', example: '의자가 불편해요.' },
    { word: '익숙하다', roman: 'iksukhada', meaning: '熟悉', pos: '形容词', example: '이곳에 익숙해요.' },
    { word: '낯설다', roman: 'natseolda', meaning: '陌生', pos: '形容词', example: '낯선 사람이에요.' },
    { word: '자유롭다', roman: 'jayuropda', meaning: '自由', pos: '形容词', example: '자유로운 시간이 필요해요.' },
    { word: '평화롭다', roman: 'pyeonghwaropda', meaning: '和平', pos: '形容词', example: '평화로운 아침이에요.' },
    { word: '활기차다', roman: 'hwalgichada', meaning: '充满活力', pos: '形容词', example: '활기찬 하루예요.' },
    { word: '조용하다', roman: 'joyonghada', meaning: '安静', pos: '形容词', example: '도서관이 조용해요.' },
    { word: '복잡하다', roman: 'bokjaphada', meaning: '复杂', pos: '形容词', example: '길이 복잡해요.' },
    { word: '단순하다', roman: 'dansunhada', meaning: '简单', pos: '形容词', example: '구조가 단순해요.' },
    { word: '효율적', roman: 'hyoyuljeok', meaning: '高效', pos: '名词', example: '효율적인 방법이에요.' },
    { word: '창의적', roman: 'changujeok', meaning: '创意', pos: '名词', example: '창의적인 아이디어예요.' },
    { word: '논리적', roman: 'nollijeok', meaning: '逻辑', pos: '名词', example: '논리적인 사고가 필요해요.' },
  ],
  // TOPIK 4级 - 中高级
  4: [
    { word: '유지하다', roman: 'yujihada', meaning: '维持', pos: '动词', example: '건강을 유지해요.' },
    { word: '보존하다', roman: 'bojonhada', meaning: '保存', pos: '动词', example: '문화재를 보존해요.' },
    { word: '보호하다', roman: 'bohohada', meaning: '保护', pos: '动词', example: '환경을 보호해요.' },
    { word: '방지하다', roman: 'bangjihada', meaning: '防止', pos: '动词', example: '사고를 방지해요.' },
    { word: '예방하다', roman: 'yebanghada', meaning: '预防', pos: '动词', example: '질병을 예방해요.' },
    { word: '치료하다', roman: 'chiryoada', meaning: '治疗', pos: '动词', example: '병을 치료해요.' },
    { word: '회복하다', roman: 'hoebokhada', meaning: '恢复', pos: '动词', example: '건강을 회복해요.' },
    { word: '예방하다', roman: 'yebanghada', meaning: '预防', pos: '动词', example: '감기를 예방해요.' },
    { word: '감염되다', roman: 'gamyeomdoeda', meaning: '感染', pos: '动词', example: '바이러스에 감염됐어요.' },
    { word: '전염되다', roman: 'jeon'yeomdoeda', meaning: '传染', pos: '动词', example: '병이 전염돼요.' },
    { word: '격리하다', roman: 'gyeollihada', meaning: '隔离', pos: '动词', example: '환자를 격리해요.' },
    { word: '면역', roman: 'myeon'yeok', meaning: '免疫', pos: '名词', example: '면역력이 떨어져요.' },
    { word: '영양', roman: 'yeong'yang', meaning: '营养', pos: '名词', example: '영양을 섭취해요.' },
    { word: '소화', roman: 'sohwa', meaning: '消化', pos: '名词', example: '소화가 잘 돼요.' },
    { word: '흡수', roman: 'heupsu', meaning: '吸收', pos: '名词', example: '영양소를 흡수해요.' },
    { word: '배출하다', roman: 'baechulhada', meaning: '排出', pos: '动词', example: '노폐물을 배출해요.' },
    { word: '순환', roman: 'sunhwan', meaning: '循环', pos: '名词', example: '혈액 순환이 돼요.' },
    { word: '호흡', roman: 'hogeup', meaning: '呼吸', pos: '名词', example: '호흡이 가빠져요.' },
    { word: '체온', roman: 'che'on', meaning: '体温', pos: '名词', example: '체온이 올라가요.' },
    { word: '혈압', roman: 'hyeolap', meaning: '血压', pos: '名词', example: '혈압이 높아요.' },
    { word: '맥박', roman: 'maekbak', meaning: '脉搏', pos: '名词', example: '맥박이 빨라요.' },
    { word: '신경', roman: 'singyeong', meaning: '神经', pos: '名词', example: '신경이 예민해요.' },
    { word: '근육', roman: 'geun'yuk', meaning: '肌肉', pos: '名词', example: '근육을 키워요.' },
    { word: '뼈', roman: 'ppyeo', meaning: '骨头', pos: '名词', example: '뼈가 튼튼해요.' },
    { word: '관절', roman: 'gwanjeol', meaning: '关节', pos: '名词', example: '관절이 아파요.' },
    { word: '피부', roman: 'pibu', meaning: '皮肤', pos: '名词', example: '피부가 건조해요.' },
    { word: '세포', roman: 'sepo', meaning: '细胞', pos: '名词', example: '세포가 재생돼요.' },
    { word: '유전', roman: 'yujeon', meaning: '遗传', pos: '名词', example: '유전적인 요인이에요.' },
    { word: '변이', roman: 'byeon'i', meaning: '变异', pos: '名词', example: '바이러스 변이가 일어나요.' },
    { word: '진화', roman: 'jinhwa', meaning: '进化', pos: '名词', example: '인류의 진화 과정이에요.' },
    { word: '적응하다', roman: 'jeogeuphada', meaning: '适应', pos: '动词', example: '환경에 적응해요.' },
    { word: '진단하다', roman: 'jindanhada', meaning: '诊断', pos: '动词', example: '병을 진단해요.' },
    { word: '처방하다', roman: 'cheobanghada', meaning: '开处方', pos: '动词', example: '약을 처방해요.' },
    { word: '수술하다', roman: 'susulhada', meaning: '手术', pos: '动词', example: '수술을 받았어요.' },
    { word: '입원하다', roman: 'ibwonhada', meaning: '住院', pos: '动词', example: '입원해야 해요.' },
    { word: '퇴원하다', roman: 'toewonhada', meaning: '出院', pos: '动词', example: '퇴원했어요.' },
    { word: '회복', roman: 'hoebok', meaning: '恢复', pos: '名词', example: '빠른 회복을 바라요.' },
    { word: '재활', roman: 'jaehwal', meaning: '康复', pos: '名词', example: '재활 치료를 받아요.' },
    { word: '운동', roman: 'undong', meaning: '运动', pos: '名词', example: '규칙적인 운동이 필요해요.' },
    { word: '스트레칭', roman: 'seuteureching', meaning: '拉伸', pos: '名词', example: '스트레칭을 해요.' },
    { word: '유산소', roman: 'yusanso', meaning: '有氧', pos: '名词', example: '유산소 운동을 해요.' },
    { word: '무산소', roman: 'musanso', meaning: '无氧', pos: '名词', example: '무산소 운동으로 근육을 키워요.' },
    { word: '식단', roman: 'sikdan', meaning: '食谱', pos: '名词', example: '건강한 식단을 유지해요.' },
    { word: '영양소', roman: 'yeong'yangso', meaning: '营养素', pos: '名词', example: '필수 영양소를 섭취해요.' },
    { word: '비타민', roman: 'bitamin', meaning: '维生素', pos: '名词', example: '비타민을 보충해요.' },
    { word: '단백질', roman: 'danbaekjil', meaning: '蛋白质', pos: '名词', example: '단백질이 풍부해요.' },
    { word: '탄수화물', roman: 'tansuhwamul', meaning: '碳水化合物', pos: '名词', example: '탄수화물을 줄여요.' },
    { word: '지방', roman: 'jibang', meaning: '脂肪', pos: '名词', example: '지방을 적게 먹어요.' },
    { word: '미네랄', roman: 'minerol', meaning: '矿物质', pos: '名词', example: '미네랄이 필요해요.' },
    { word: '식이섬유', roman: 'sigiseomyu', meaning: '膳食纤维', pos: '名词', example: '식이섬유가 풍부해요.' },
    { word: '항산화', roman: 'hongsanhwa', meaning: '抗氧化', pos: '名词', example: '항산화 식품이 좋아요.' },
  ],
  // TOPIK 5级 - 高级
  5: [
    { word: '주관적', roman: 'jugwanjeok', meaning: '主观', pos: '名词', example: '주관적인 의견이에요.' },
    { word: '객관적', roman: 'gaekgwanjeok', meaning: '客观', pos: '名词', example: '객관적인 판단이 필요해요.' },
    { word: '이성적', roman: 'iseongjeok', meaning: '理性', pos: '名词', example: '이성적인 접근이 필요해요.' },
    { word: '감성적', roman: 'gapseongjeok', meaning: '感性', pos: '名词', example: '감성적인 표현이에요.' },
    { word: '합리적', roman: 'haprijeok', meaning: '合理', pos: '名词', example: '합리적인 가격이에요.' },
    { word: '비합리적', roman: 'bihaprijeok', meaning: '不合理', pos: '名词', example: '비합리적인 제도예요.' },
    { word: '윤리적', roman: 'yullijeok', meaning: '伦理', pos: '名词', example: '윤리적 문제가 있어요.' },
    { word: '도덕적', roman: 'dodeokjeok', meaning: '道德', pos: '名词', example: '도덕적 책임이 있어요.' },
    { word: '법적', roman: 'beopjeok', meaning: '法律', pos: '名词', example: '법적 조치를 취해요.' },
    { word: '사회적', roman: 'sahoejeok', meaning: '社会', pos: '名词', example: '사회적 문제예요.' },
    { word: '문화적', roman: 'munhwa'jeok', meaning: '文化', pos: '名词', example: '문화적 차이가 있어요.' },
    { word: '역사적', roman: 'yeoksajeok', meaning: '历史', pos: '名词', example: '역사적 사실이에요.' },
    { word: '정치적', roman: 'jeongchijeok', meaning: '政治', pos: '名词', example: '정치적 중립을 지켜요.' },
    { word: '경제적', roman: 'gyeongjejeok', meaning: '经济', pos: '名词', example: '경제적 효과가 커요.' },
    { word: '환경적', roman: 'hwangyeongjeok', meaning: '环境', pos: '名词', example: '환경적 영향을 고려해요.' },
    { word: '기술적', roman: 'gisuljeok', meaning: '技术', pos: '名词', example: '기술적 한계가 있어요.' },
    { word: '과학적', roman: 'gwahakjeok', meaning: '科学', pos: '名词', example: '과학적 근거가 있어요.' },
    { word: '철학적', roman: 'cheolhakjeok', meaning: '哲学', pos: '名词', example: '철학적 질문이에요.' },
    { word: '심리적', roman: 'simrijeok', meaning: '心理', pos: '名词', example: '심리적 압박이 커요.' },
    { word: '생리적', roman: 'saengrijeok', meaning: '生理', pos: '名词', example: '생리적 현상이에요.' },
    { word: '물리적', roman: 'mulrijeok', meaning: '物理', pos: '名词', example: '물리적 충격이에요.' },
    { word: '화학적', roman: 'hwahakjeok', meaning: '化学', pos: '名词', example: '화학적 반응이에요.' },
    { word: '생물학적', roman: 'saengmulhakjeok', meaning: '生物', pos: '名词', example: '생물학적 다양성이에요.' },
    { word: '지리적', roman: 'jirijeok', meaning: '地理', pos: '名词', example: '지리적 조건이 좋아요.' },
    { word: '기후적', roman: 'gihujeok', meaning: '气候', pos: '名词', example: '기후적 요인이에요.' },
    { word: '인구적', roman: 'ingujeok', meaning: '人口', pos: '名词', example: '인구적 변화가 있어요.' },
    { word: '산업적', roman: 'san'eopjeok', meaning: '产业', pos: '名词', example: '산업적 발전이에요.' },
    { word: '농업적', roman: 'nong'eopjeok', meaning: '农业', pos: '名词', example: '농업적 생산이에요.' },
    { word: '상업적', roman: 'sang'eopjeok', meaning: '商业', pos: '名词', example: '상업적 목적이에요.' },
    { word: '교육적', roman: 'gyoyukjeok', meaning: '教育', pos: '名词', example: '교육적 효과가 커요.' },
    { word: '예술적', roman: 'yesuljeok', meaning: '艺术', pos: '名词', example: '예술적 가치가 있어요.' },
    { word: '종교적', roman: 'jonggyojeok', meaning: '宗教', pos: '名词', example: '종교적 신념이에요.' },
    { word: '민족적', roman: 'minjokjeok', meaning: '民族', pos: '名词', example: '민족적 자긍심이에요.' },
    { word: '국가적', roman: 'gukgajeok', meaning: '国家', pos: '名词', example: '국가적 차원의 문제예요.' },
    { word: '국제적', roman: 'gukjejeok', meaning: '国际', pos: '名词', example: '국제적 협력이 필요해요.' },
    { word: '세계적', roman: 'segyejeok', meaning: '世界', pos: '名词', example: '세계적 문제예요.' },
    { word: '지역적', roman: 'jiyeokjeok', meaning: '地区', pos: '名词', example: '지역적 특성이 있어요.' },
    { word: '개인적', roman: 'gaeinjeok', meaning: '个人', pos: '名词', example: '개인적 취향이에요.' },
    { word: '집단적', roman: 'jipdanjeok', meaning: '集体', pos: '名词', example: '집단적 행동이에요.' },
    { word: '대중적', roman: 'daejoongjeok', meaning: '大众', pos: '名词', example: '대중적 인기가 있어요.' },
    { word: '전문적', roman: 'jeonmunjeok', meaning: '专业', pos: '名词', example: '전문적 지식이 필요해요.' },
    { word: ' 业余的', roman: 'amachueojeok', meaning: '业余', pos: '名词', example: '아마추어적 수준이에요.' },
    { word: '전통적', roman: 'jeontongjeok', meaning: '传统', pos: '名词', example: '전통적 가치예요.' },
    { word: '현대적', roman: 'hyeondaejeok', meaning: '现代', pos: '名词', example: '현대적 감각이에요.' },
    { word: '미래적', roman: 'miraejeok', meaning: '未来', pos: '名词', example: '미래지향적 사고예요.' },
    { word: '가치관', roman: 'gachigwan', meaning: '价值观', pos: '名词', example: '가치관이 달라요.' },
    { word: '세계관', roman: 'segyegwan', meaning: '世界观', pos: '名词', example: '세계관이 넓어요.' },
    { word: '인생관', roman: 'insaenggwan', meaning: '人生观', pos: '名词', example: '인생관이 확고해요.' },
    { word: '철학', roman: 'cheolhak', meaning: '哲学', pos: '名词', example: '동양 철학을 공부해요.' },
    { word: '사상', roman: 'sasang', meaning: '思想', pos: '名词', example: '선진 사상을 받아들여요.' },
    { word: '이념', roman: 'inyeom', meaning: '理念', pos: '名词', example: '정치 이념이 달라요.' },
  ],
  // TOPIK 6级 - 最高级
  6: [
    { word: '모순', roman: 'mosun', meaning: '矛盾', pos: '名词', example: '모순된 상황이에요.' },
    { word: '역설', roman: 'yeokseol', meaning: '悖论/反语', pos: '名词', example: '역설적 표현이에요.' },
    { word: '아이러니', roman: 'aireoni', meaning: '讽刺', pos: '名词', example: '아이러니한 상황이에요.' },
    { word: '패러독스', roman: 'paerodokseu', meaning: '悖论', pos: '名词', example: '시간의 패러독스예요.' },
    { word: '딜레마', roman: 'dilrema', meaning: '困境', pos: '名词', example: '윤리적 딜레마에 빠졌어요.' },
    { word: '갈등', roman: 'galdeung', meaning: '矛盾/冲突', pos: '名词', example: '이해관계의 갈등이에요.' },
    { word: '대립', roman: 'daerip', meaning: '对立', pos: '名词', example: '의견 대립이 심해요.' },
    { word: '충돌', roman: 'chungdol', meaning: '冲突', pos: '名词', example: '이익 충돌이 일어나요.' },
    { word: '타협', roman: 'tahyeop', meaning: '妥协', pos: '名词', example: '타협점을 찾아요.' },
    { word: '양보', roman: 'yangbo', meaning: '让步', pos: '名词', example: '서로 양보해요.' },
    { word: '절충', roman: 'jeolchung', meaning: '折中', pos: '名词', example: '절충안을 제시해요.' },
    { word: '조율', roman: 'joyul', meaning: '协调', pos: '名词', example: '의견을 조율해요.' },
    { word: '중재', roman: 'jungjae', meaning: '仲裁', pos: '名词', example: '중재자가 필요해요.' },
    { word: '화해', roman: 'hawahae', meaning: '和解', pos: '名词', example: '화해하고 지내요.' },
    { word: '용서', roman: 'yongseo', meaning: '宽恕', pos: '名词', example: '용서를 구해요.' },
    { word: '관용', roman: 'gwanyong', meaning: '宽容', pos: '名词', example: '관용의 정신이 필요해요.' },
    { word: '포용', roman: 'poyong', meaning: '包容', pos: '名词', example: '포용력이 있는 사람이에요.' },
    { word: '수용', roman: 'suyong', meaning: '接纳', pos: '名词', example: '다름을 수용해요.' },
    { word: '거부', roman: 'geobu', meaning: '拒绝', pos: '名词', example: '요청을 거부했어요.' },
    { word: '항의', roman: 'hang'ui', meaning: '抗议', pos: '名词', example: '항의 서한을 보냈어요.' },
    { word: '반발', roman: 'banbal', meaning: '反抗', pos: '名词', example: '반발이 거세요.' },
    { word: '저항', roman: 'jeohang', meaning: '抵抗', pos: '名词', example: '저항 세력이 커요.' },
    { word: '투쟁', roman: 'tusaeng', meaning: '斗争', pos: '名词', example: '투쟁이 장기화돼요.' },
    { word: '혁명', roman: 'hyeongmyeong', meaning: '革命', pos: '名词', example: '산업 혁명이에요.' },
    { word: '반란', roman: 'ballan', meaning: '叛乱', pos: '名词', example: '반란이 일어났어요.' },
    { word: '쿠데타', roman: 'kudeta', meaning: '政变', pos: '名词', example: '쿠데타가 발생했어요.' },
    { word: '독립', roman: 'dongnip', meaning: '独立', pos: '名词', example: '독립 운동이에요.' },
    { word: '해방', roman: 'haebang', meaning: '解放', pos: '名词', example: '해방된 기분이에요.' },
    { word: '자주', roman: 'jaju', meaning: '自主', pos: '名词', example: '자주 독립이에요.' },
    { word: '주권', roman: 'jugwon', meaning: '主权', pos: '名词', example: '주권을 지켜요.' },
    { word: '민주', roman: 'minju', meaning: '民主', pos: '名词', example: '민주주의 사회예요.' },
    { word: '자유', roman: 'jayu', meaning: '自由', pos: '名词', example: '자유를 누려요.' },
    { word: '평등', roman: 'pyeongdeung', meaning: '平等', pos: '名词', example: '평등한 기회예요.' },
    { word: '박애', roman: 'bagae', meaning: '博爱', pos: '名词', example: '박애 정신을 실천해요.' },
    { word: '공익', roman: 'gong'ik', meaning: '公益', pos: '名词', example: '공익을 위해 봉사해요.' },
    { word: '사익', roman: 'sa'ik', meaning: '私益', pos: '名词', example: '사익을 추구해요.' },
    { word: '공동체', roman: 'gongdongche', meaning: '共同体', pos: '名词', example: '공동체 의식이 필요해요.' },
    { word: '연대', roman: 'yeondae', meaning: '团结', pos: '名词', example: '연대 의식을 가져요.' },
    { word: '협동', roman: 'hyeopdong', meaning: '协同', pos: '名词', example: '협동 작업이에요.' },
    { word: '협력', roman: 'hyeolryeok', meaning: '协力', pos: '名词', example: '협력 관계를 맺어요.' },
    { word: '제휴', roman: 'jehwi', meaning: '联盟/合作', pos: '名词', example: '제휴를 맺었어요.' },
    { word: '동맹', roman: 'dongmaeng', meaning: '同盟', pos: '名词', example: '동맹을 체결했어요.' },
    { word: '연합', roman: 'yeonhap', meaning: '联合', pos: '名词', example: '연합군이에요.' },
    { word: '통합', roman: 'tonghap', meaning: '整合', pos: '名词', example: '시스템 통합이에요.' },
    { word: '융합', roman: 'yunghap', meaning: '融合', pos: '名词', example: '기술 융합이에요.' },
    { word: '복합', roman: 'bokhap', meaning: '复合', pos: '名词', example: '복합 문화 공간이에요.' },
    { word: '종합', roman: 'jonghap', meaning: '综合', pos: '名词', example: '종합적인 판단이에요.' },
    { word: '일체', roman: 'ilche', meaning: '一体', pos: '名词', example: '일체가 돼요.' },
    { word: '통일', roman: 'tong'il', meaning: '统一', pos: '名词', example: '통일을 염원해요.' },
    { word: '단결', roman: 'dangyeol', meaning: '团结', pos: '名词', example: '단결력이 강해요.' },
    { word: '응집', roman: 'eungjip', meaning: '凝聚', pos: '名词', example: '응집력이 높아요.' },
  ],
};

// ===== 3. 日常生活常用单词（按主题分类，丰富收录） =====
window.DAILY_VOCAB = {
  '饮食': [
    { word: '김치', meaning: '泡菜', roman: 'gimchi' },
    { word: '비빔밥', meaning: '拌饭', roman: 'bibimbap' },
    { word: '불고기', meaning: '烤肉', roman: 'bulgogi' },
    { word: '떡볶이', meaning: '炒年糕', roman: 'tteokbokki' },
    { word: '라면', meaning: '拉面', roman: 'ramyeon' },
    { word: '삼겹살', meaning: '五花肉', roman: 'samgyeopsal' },
    { word: '된장찌개', meaning: '大酱汤', roman: 'doenjangjjigae' },
    { word: '김밥', meaning: '紫菜包饭', roman: 'gimbap' },
    { word: '족발', meaning: '猪蹄', roman: 'jokbal' },
    { word: '치킨', meaning: '炸鸡', roman: 'chikin' },
    { word: '삼계탕', meaning: '参鸡汤', roman: 'samgyetang' },
    { word: '냉면', meaning: '冷面', roman: 'naengmyeon' },
    { word: '갈비', meaning: '排骨', roman: 'galbi' },
    { word: '해장국', meaning: '解酒汤', roman: 'haejangguk' },
    { word: '순두부', meaning: '嫩豆腐', roman: 'sundubu' },
    { word: '떡', meaning: '年糕', roman: 'tteok' },
    { word: '국수', meaning: '面条', roman: 'guksu' },
    { word: '죽', meaning: '粥', roman: 'juk' },
    { word: '전', meaning: '煎饼', roman: 'jeon' },
    { word: '찌개', meaning: '汤', roman: 'jjigae' },
  ],
  '交通': [
    { word: '지하철', meaning: '地铁', roman: 'jihacheol' },
    { word: '버스', meaning: '公交车', roman: 'beoseu' },
    { word: '택시', meaning: '出租车', roman: 'taeksi' },
    { word: '기차', meaning: '火车', roman: 'gicha' },
    { word: '비행기', meaning: '飞机', roman: 'bihaenggi' },
    { word: '배', meaning: '船', roman: 'bae' },
    { word: '자전거', meaning: '自行车', roman: 'jajeongeo' },
    { word: '자동차', meaning: '汽车', roman: 'jadongcha' },
    { word: '도보', meaning: '步行', roman: 'dobo' },
    { word: '운전', meaning: '驾驶', roman: 'unjeon' },
    { word: '정류장', meaning: '车站', roman: 'jeongryujang' },
    { word: '승차권', meaning: '车票', roman: 'seungchagwon' },
    { word: '환승', meaning: '换乘', roman: 'hwanseung' },
    { word: '출구', meaning: '出口', roman: 'chulgu' },
    { word: '입구', meaning: '入口', roman: 'ipgu' },
    { word: '횡단보도', meaning: '人行道', roman: 'hoengdanbodo' },
    { word: '신호등', meaning: '红绿灯', roman: 'sinhodeung' },
    { word: '고속도로', meaning: '高速公路', roman: 'gosokdoro' },
    { word: '주차장', meaning: '停车场', roman: 'juchajang' },
    { word: '요금', meaning: '费用', roman: 'yogeum' },
  ],
  '购物': [
    { word: '백화점', meaning: '百货商店', roman: 'baekhwajeom' },
    { word: '마트', meaning: '大型超市', roman: 'mateu' },
    { word: '편의점', meaning: '便利店', roman: 'pyeon'ijeom' },
    { word: '시장', meaning: '市场', roman: 'sijang' },
    { word: '가격', meaning: '价格', roman: 'gagyeok' },
    { word: '할인', meaning: '折扣', roman: 'harin' },
    { word: '세일', meaning: '促销', roman: 'seil' },
    { word: '무료', meaning: '免费', roman: 'muryo' },
    { word: '결제', meaning: '结账', roman: 'gyeolje' },
    { word: '현금', meaning: '现金', roman: 'hyeongeum' },
    { word: '카드', meaning: '卡', roman: 'kadeu' },
    { word: '영수증', meaning: '收据', roman: 'yeongsujeung' },
    { word: '교환', meaning: '交换', roman: 'gyohwan' },
    { word: '환불', meaning: '退款', roman: 'hwanbul' },
    { word: '포장', meaning: '包装', roman: 'pojang' },
    { word: '배송', meaning: '配送', roman: 'baesong' },
    { word: '사이즈', meaning: '尺寸', roman: 'saijeu' },
    { word: '색깔', meaning: '颜色', roman: 'saekkal' },
    { word: '디자인', meaning: '设计', roman: 'dijain' },
    { word: '품질', meaning: '质量', roman: 'pumjil' },
  ],
  '学校': [
    { word: '교실', meaning: '教室', roman: 'gyosil' },
    { word: '교수', meaning: '教授', roman: 'gyosu' },
    { word: '강의', meaning: '讲课', roman: 'gang'ui' },
    { word: '수업', meaning: '上课', roman: 'su'eop' },
    { word: '숙제', meaning: '作业', roman: 'sukje' },
    { word: '과제', meaning: '课题', roman: 'gwaje' },
    { word: '시험', meaning: '考试', roman: 'siheom' },
    { word: '성적', meaning: '成绩', roman: 'seongjeok' },
    { word: '졸업', meaning: '毕业', roman: 'joreop' },
    { word: '입학', meaning: '入学', roman: 'iphak' },
    { word: '도서관', meaning: '图书馆', roman: 'doseogwan' },
    { word: '기숙사', meaning: '宿舍', roman: 'gisuksa' },
    { word: '동아리', meaning: '社团', roman: 'dong'ari' },
    { word: '학점', meaning: '学分', roman: 'hakjeom' },
    { word: '전공', meaning: '专业', roman: 'jeongong' },
    { word: '복수전공', meaning: '双专业', roman: 'boksujeongong' },
    { word: '부전공', meaning: '辅修', roman: 'bujeongong' },
    { word: '장학금', meaning: '奖学金', roman: 'janghakgeum' },
    { word: '등록금', meaning: '学费', roman: 'deungrokgeum' },
    { word: '강의실', meaning: '讲堂', roman: 'gang'uisil' },
  ],
  '职场': [
    { word: '회사', meaning: '公司', roman: 'hoesa' },
    { word: '직장', meaning: '职场', roman: 'jikjang' },
    { word: '상사', meaning: '上司', roman: 'sangsa' },
    { word: '부하', meaning: '下属', roman: 'buha' },
    { word: '동료', meaning: '同事', roman: 'dongryo' },
    { word: '회의', meaning: '会议', roman: 'hoeui' },
    { word: '보고서', meaning: '报告', roman: 'bogoseo' },
    { word: '프로젝트', meaning: '项目', roman: 'peurojeketeu' },
    { word: '마감', meaning: '截止', roman: 'magam' },
    { word: '초과근무', meaning: '加班', roman: 'chogageunmu' },
    { word: '월급', meaning: '月薪', roman: 'wolgeup' },
    { word: '연봉', meaning: '年薪', roman: 'yeonbong' },
    { word: '퇴직', meaning: '退休', roman: 'toejik' },
    { word: '취직', meaning: '就业', roman: 'chwijik' },
    { word: '면접', meaning: '面试', roman: 'myeonjeop' },
    { word: '이력서', meaning: '简历', roman: 'iryeokseo' },
    { word: '경력', meaning: '经历', roman: 'gyeongryeok' },
    { word: '승진', meaning: '升职', roman: 'seungjin' },
    { word: '인사과', meaning: '人事科', roman: 'insagwa' },
    { word: '복지', meaning: '福利', roman: 'bokji' },
  ],
  '天气自然': [
    { word: '날씨', meaning: '天气', roman: 'nalssi' },
    { word: '비', meaning: '雨', roman: 'bi' },
    { word: '눈', meaning: '雪', roman: 'nun' },
    { word: '바람', meaning: '风', roman: 'baram' },
    { word: '구름', meaning: '云', roman: 'gureum' },
    { word: '해', meaning: '太阳', roman: 'hae' },
    { word: '달', meaning: '月亮', roman: 'dal' },
    { word: '별', meaning: '星星', roman: 'byeol' },
    { word: '하늘', meaning: '天空', roman: 'haneul' },
    { word: '온도', meaning: '温度', roman: 'ondo' },
    { word: '습도', meaning: '湿度', roman: 'seupdo' },
    { word: '계절', meaning: '季节', roman: 'gyejeol' },
    { word: '봄', meaning: '春天', roman: 'bom' },
    { word: '여름', meaning: '夏天', roman: 'yeoreum' },
    { word: '가을', meaning: '秋天', roman: 'ga'eul' },
    { word: '겨울', meaning: '冬天', roman: 'gyeoul' },
    { word: '산', meaning: '山', roman: 'san' },
    { word: '강', meaning: '江', roman: 'gang' },
    { word: '바다', meaning: '海', roman: 'bada' },
    { word: '꽃', meaning: '花', roman: 'kkot' },
  ],
  '身体健康': [
    { word: '머리', meaning: '头', roman: 'meori' },
    { word: '얼굴', meaning: '脸', roman: 'eolgul' },
    { word: '눈', meaning: '眼睛', roman: 'nun' },
    { word: '코', meaning: '鼻子', roman: 'ko' },
    { word: '입', meaning: '嘴', roman: 'ip' },
    { word: '귀', meaning: '耳朵', roman: 'gwi' },
    { word: '손', meaning: '手', roman: 'son' },
    { word: '발', meaning: '脚', roman: 'bal' },
    { word: '팔', meaning: '胳膊', roman: 'pal' },
    { word: '다리', meaning: '腿', roman: 'dari' },
    { word: '배', meaning: '肚子', roman: 'bae' },
    { word: '등', meaning: '背', roman: 'deung' },
    { word: '심장', meaning: '心脏', roman: 'simjang' },
    { word: '폐', meaning: '肺', roman: 'pye' },
    { word: '간', meaning: '肝', roman: 'gan' },
    { word: '위', meaning: '胃', roman: 'wi' },
    { word: '피', meaning: '血', roman: 'pi' },
    { word: '뼈', meaning: '骨', roman: 'ppyeo' },
    { word: '살', meaning: '肉', roman: 'sal' },
    { word: '피부', meaning: '皮肤', roman: 'pibu' },
  ],
  '情感': [
    { word: '기쁨', meaning: '喜悦', roman: 'gippeum' },
    { word: '슬픔', meaning: '悲伤', roman: 'seulpeum' },
    { word: '분노', meaning: '愤怒', roman: 'bunno' },
    { word: '두려움', meaning: '恐惧', roman: 'duryeoum' },
    { word: '놀람', meaning: '惊讶', roman: 'nollam' },
    { word: '사랑', meaning: '爱', roman: 'sarang' },
    { word: '증오', meaning: '憎恨', roman: 'jeung'o' },
    { word: '질투', meaning: '嫉妒', roman: 'jiltu' },
    { word: '부러움', meaning: '羡慕', roman: 'bureoum' },
    { word: '그리움', meaning: '思念', roman: 'geurium' },
    { word: '외로움', meaning: '孤独', roman: 'oeroum' },
    { word: '편안함', meaning: '安心', roman: 'pyeon'anham' },
    { word: '불안', meaning: '不安', roman: 'buran' },
    { word: '긴장', meaning: '紧张', roman: 'ginjang' },
    { word: '이완', meaning: '放松', roman: 'iwan' },
    { word: '흥분', meaning: '兴奋', roman: 'heungbun' },
    { word: '차분', meaning: '平静', roman: 'chabun' },
    { word: '실망', meaning: '失望', roman: 'silmang' },
    { word: '희망', meaning: '希望', roman: 'huimang' },
    { word: '절망', meaning: '绝望', roman: 'jeolmang' },
  ],
  '时间': [
    { word: '아침', meaning: '早晨', roman: 'achim' },
    { word: '점심', meaning: '中午', roman: 'jeomsim' },
    { word: '저녁', meaning: '晚上', roman: 'jeonyeok' },
    { word: '밤', meaning: '夜里', roman: 'bam' },
    { word: '새벽', meaning: '凌晨', roman: 'saebyeok' },
    { word: '어제', meaning: '昨天', roman: 'eoje' },
    { word: '오늘', meaning: '今天', roman: 'oneul' },
    { word: '내일', meaning: '明天', roman: 'naeil' },
    { word: '모레', meaning: '后天', roman: 'more' },
    { word: '어그저께', meaning: '前天', roman: 'eogeujeokke' },
    { word: '주말', meaning: '周末', roman: 'jumal' },
    { word: '평일', meaning: '工作日', roman: 'pyeong'il' },
    { word: '이번 주', meaning: '这周', roman: 'ibeon ju' },
    { word: '저번 주', meaning: '上周', roman: 'jeobeon ju' },
    { word: '다음 주', meaning: '下周', roman: 'daeum ju' },
    { word: '이번 달', meaning: '这个月', roman: 'ibeon dal' },
    { word: '올해', meaning: '今年', roman: 'olhae' },
    { word: '작년', meaning: '去年', roman: 'jaknyeon' },
    { word: '내년', meaning: '明年', roman: 'naenyeon' },
    { word: '시간', meaning: '时间', roman: 'sigan' },
  ],
};

// 汇总所有日常词汇为一个数组（便于练习抽题）
window.DAILY_VOCAB_ALL = Object.entries(window.DAILY_VOCAB).flatMap(([cat, list]) =>
  list.map(v => ({ ...v, category: cat }))
);
